### PR TITLE
stage front door preview

### PR DESCRIPTION
**Pull request by rloutlaw**

### CODE REVIEW

**Comment by rloutlaw** [comment]
Do not merge.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/index-frontdoor.yml](https://github.com/rloutlaw/azure-docs-sdk-java-1/blob/rloutlaw/java-ms-frontdoor/docs-ref-conceptual/index-frontdoor.yml) | :x:Error | | [Details](#user-content-docs-ref-conceptual%2Findex-frontdoor.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="docs-ref-conceptual%2Findex-frontdoor.yml"></a>
### [docs-ref-conceptual/index-frontdoor.yml](https://github.com/rloutlaw/azure-docs-sdk-java-1/blob/rloutlaw/java-ms-frontdoor/docs-ref-conceptual/index-frontdoor.yml)
 - **[Error]** Unable to load file: docs-ref-conceptual/index-frontdoor.yml via processor: ManagedReferenceDocumentProcessor: (Line: 6, Col: 1, Idx: 238) - (Line: 6, Col: 4, Idx: 241): Expected &#39;StreamEnd&#39;, got &#39;DocumentStart&#39; (at Line: 6, Col: 1, Idx: 238).
 - **[Warning]** Please add `YamlMime` as the first line of file, e.g.: `### YamlMime:ManagedReference`, otherwise the file will be not treated as ManagedReference source file in near future.

<a name=""></a>
### []()
 - **[Error]** YamlDotNet.Core.YamlException: (Line: 6, Col: 1, Idx: 238) - (Line: 6, Col: 4, Idx: 241): Expected &#39;StreamEnd&#39;, got &#39;DocumentStart&#39; (at Line: 6, Col: 1, Idx: 238).
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.GetInnerContexts(DocumentBuildParameters parameters, IEnumerable`1 processors, TemplateProcessor templateProcessor, IHostServiceCreator creator)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.BuildCore(DocumentBuildParameters parameters)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.BuildCore(DocumentBuildParameters parameter, IMarkdownServiceProvider markdownServiceProvider, BuildInfo currentBuildInfo, BuildInfo lastBuildInfo)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.Build(IList`1 parameters, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C23%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201808231645104452-584%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UGs7GrIInu%2FeSkV0q%2BW5JNFyovLEHjPpWqlNCrSQFH0%3D&st=2018-08-23T16%3A45%3A50Z&se=2018-09-23T16%3A50%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/index-frontdoor.md](https://github.com/rloutlaw/azure-docs-sdk-java-1/blob/rloutlaw/java-ms-frontdoor/docs-ref-conceptual/index-frontdoor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/index-frontdoor?view=azure-java-stable&branch=pr-en-us-584) (azure-java-stable) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C23%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201808231653177649-584%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=J16pJjwpReuhiDgfnayPGEqbaKDBV8LR68ZwGBgttlQ%3D&st=2018-08-23T18%3A50%3A31Z&se=2018-09-23T18%3A55%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by brunoborges** [comment]
@rloutlaw r u fine if I merge this under the new branch `java-frontdoor` ?

**Comment by rloutlaw** [comment]
@brunoborges  totally go for it

**Pull request merged**
