### PR TITLE
fixes for CATS report

### PR DESCRIPTION
**Pull request by craigcaseyMSFT**
Fixing various CATS report errors per https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1548981

### CODE REVIEW

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[8f6d22b](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/pull/882/commits/8f6d22b1123ff3b2db3c8935677f8a8fbe82b618)_: 

:clock10: **Full build**: the average full build time is _71 min(s) 47 sec(s)_, this is based on the last _297_ build(s) for this repository.

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[8f6d22b](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/pull/882/commits/8f6d22b1123ff3b2db3c8935677f8a8fbe82b618)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-autogen/com.microsoft.azure.storage.blob.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/com.microsoft.azure.storage.blob.yml) | :x:Error | | [Details](#user-content-0780b884-083ee567)
[docs-ref-autogen/overview/Storage/Client.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/overview/Storage/Client.yml) | :x:Error | | [Details](#user-content-80634b27-083ee567)
[]() | :x:Error | | [Details](#user-content-083ee567)

<a id="0780b884-083ee567"></a>
### [docs-ref-autogen/com.microsoft.azure.storage.blob.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/com.microsoft.azure.storage.blob.yml)
 - **[Error]** `````Unable to load file 'docs-ref-autogen/com.microsoft.azure.storage.blob.yml' via processor 'ManagedReferenceDocumentProcessor': (Line: 158, Col: 553, Idx: 11537) - (Line: 158, Col: 554, Idx: 11538): While scanning a block scalar, did not find expected comment or line break.`````

<a id="80634b27-083ee567"></a>
### [docs-ref-autogen/overview/Storage/Client.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/overview/Storage/Client.yml)
 - **[Error]** `````Error transforming model "W:\qxqx-o-unknown\raw-\4k4lcsti.qzh\rawmodel\stable\api\overview\azure\Storage\Client.raw.json" generated from "docs-ref-autogen/overview/Storage/Client.yml" using "ManagedReference.html.primary.js". Error running Transform function inside template preprocessor: `````

<a id="083ee567"></a>
###
 - **[Error]** `````Error transforming model "W:\qxqx-o-unknown\raw-\4k4lcsti.qzh\rawmodel\stable\api\overview\azure\Storage\Client.raw.json" generated from "docs-ref-autogen/overview/Storage/Client.yml" using "ManagedReference.html.primary.js". Error running Transform function inside template preprocessor: `````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C27%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201906272255018927-882%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FzJ5AJWLragKFnkmjVgnLk%2BGfBfSW48J4CI%2BBbtaNy4%3D&st=2019-06-27T23%3A42%3A58Z&se=2019-07-28T23%3A47%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[8f6d22b](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/pull/882/commits/8f6d22b1123ff3b2db3c8935677f8a8fbe82b618)_: 

:clock10: **Full build**: the average full build time is _71 min(s) 47 sec(s)_, this is based on the last _297_ build(s) for this repository.

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[8f6d22b](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/pull/882/commits/8f6d22b1123ff3b2db3c8935677f8a8fbe82b618)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-autogen/com.microsoft.azure.storage.blob.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/com.microsoft.azure.storage.blob.yml) | :x:Error | | [Details](#user-content-0780b884-8c6aa727)
[docs-ref-autogen/overview/Storage/Client.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/overview/Storage/Client.yml) | :x:Error | | [Details](#user-content-80634b27-8c6aa727)
[]() | :x:Error | | [Details](#user-content-8c6aa727)

<a id="0780b884-8c6aa727"></a>
### [docs-ref-autogen/com.microsoft.azure.storage.blob.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/com.microsoft.azure.storage.blob.yml)
 - **[Error]** `````Unable to load file 'docs-ref-autogen/com.microsoft.azure.storage.blob.yml' via processor 'ManagedReferenceDocumentProcessor': (Line: 158, Col: 553, Idx: 11537) - (Line: 158, Col: 554, Idx: 11538): While scanning a block scalar, did not find expected comment or line break.`````

<a id="80634b27-8c6aa727"></a>
### [docs-ref-autogen/overview/Storage/Client.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/overview/Storage/Client.yml)
 - **[Error]** `````Error transforming model "W:\qlfi-o-ffd5b639\raw-\unsikmyn.43h\rawmodel\stable\api\overview\azure\Storage\Client.raw.json" generated from "docs-ref-autogen/overview/Storage/Client.yml" using "ManagedReference.html.primary.js". Error running Transform function inside template preprocessor: `````

<a id="8c6aa727"></a>
###
 - **[Error]** `````Error transforming model "W:\qlfi-o-ffd5b639\raw-\unsikmyn.43h\rawmodel\stable\api\overview\azure\Storage\Client.raw.json" generated from "docs-ref-autogen/overview/Storage/Client.yml" using "ManagedReference.html.primary.js". Error running Transform function inside template preprocessor: `````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C28%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201906280005118493-882%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=H%2B%2BYll9U3CV4zy2uN%2Bcod49A6WO%2Bw3xYj%2FEfU5kkwII%3D&st=2019-06-28T00%3A57%3A21Z&se=2019-07-29T01%3A02%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[8f6d22b](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/pull/882/commits/8f6d22b1123ff3b2db3c8935677f8a8fbe82b618)_: 

:clock10: **Full build**: the average full build time is _71 min(s) 47 sec(s)_, this is based on the last _297_ build(s) for this repository.

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[8f6d22b](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/pull/882/commits/8f6d22b1123ff3b2db3c8935677f8a8fbe82b618)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-autogen/com.microsoft.azure.storage.blob.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/com.microsoft.azure.storage.blob.yml) | :x:Error | | [Details](#user-content-0780b884-ab3999d9)
[docs-ref-autogen/overview/Storage/Client.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/overview/Storage/Client.yml) | :x:Error | | [Details](#user-content-80634b27-ab3999d9)
[]() | :x:Error | | [Details](#user-content-ab3999d9)

<a id="0780b884-ab3999d9"></a>
### [docs-ref-autogen/com.microsoft.azure.storage.blob.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/com.microsoft.azure.storage.blob.yml)
 - **[Error]** `````Unable to load file 'docs-ref-autogen/com.microsoft.azure.storage.blob.yml' via processor 'ManagedReferenceDocumentProcessor': (Line: 158, Col: 553, Idx: 11537) - (Line: 158, Col: 554, Idx: 11538): While scanning a block scalar, did not find expected comment or line break.`````

<a id="80634b27-ab3999d9"></a>
### [docs-ref-autogen/overview/Storage/Client.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/overview/Storage/Client.yml)
 - **[Error]** `````Error transforming model "W:\42j1-o-a72c9a26\raw-\c4mnrlcs.qkz\rawmodel\stable\api\overview\azure\Storage\Client.raw.json" generated from "docs-ref-autogen/overview/Storage/Client.yml" using "ManagedReference.html.primary.js". Error running Transform function inside template preprocessor: `````

<a id="ab3999d9"></a>
###
 - **[Error]** `````Error transforming model "W:\42j1-o-a72c9a26\raw-\c4mnrlcs.qkz\rawmodel\stable\api\overview\azure\Storage\Client.raw.json" generated from "docs-ref-autogen/overview/Storage/Client.yml" using "ManagedReference.html.primary.js". Error running Transform function inside template preprocessor: `````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C28%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201906281316299189-882%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bl1mfkXjz27tA0JzLDEYugI0Jlht%2BeFc1PNIFCNi5t0%3D&st=2019-06-28T14%3A05%3A44Z&se=2019-07-29T14%3A10%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[b5b7386](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/pull/882/commits/b5b7386435b2d07d92ef93eb4d97fceae7a3ee4d)_: 

:clock10: **Full build**: the average full build time is _71 min(s) 47 sec(s)_, this is based on the last _297_ build(s) for this repository.

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[b5b7386](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/pull/882/commits/b5b7386435b2d07d92ef93eb4d97fceae7a3ee4d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-autogen/com.microsoft.azure.storage.blob.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/com.microsoft.azure.storage.blob.yml) | :x:Error | | [Details](#user-content-0780b884-531370f3)
[docs-ref-autogen/overview/Storage/Client.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/overview/Storage/Client.yml) | :x:Error | | [Details](#user-content-80634b27-531370f3)
[]() | :x:Error | | [Details](#user-content-531370f3)

<a id="0780b884-531370f3"></a>
### [docs-ref-autogen/com.microsoft.azure.storage.blob.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/com.microsoft.azure.storage.blob.yml)
 - **[Error]** `````Unable to load file 'docs-ref-autogen/com.microsoft.azure.storage.blob.yml' via processor 'ManagedReferenceDocumentProcessor': (Line: 158, Col: 569, Idx: 11553) - (Line: 158, Col: 570, Idx: 11554): While scanning a block scalar, did not find expected comment or line break.`````

<a id="80634b27-531370f3"></a>
### [docs-ref-autogen/overview/Storage/Client.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-autogen/overview/Storage/Client.yml)
 - **[Error]** `````Error transforming model "W:\vf54-o-9953c818\raw-\n1vbh3i0.h3i\rawmodel\stable\api\overview\azure\Storage\Client.raw.json" generated from "docs-ref-autogen/overview/Storage/Client.yml" using "ManagedReference.html.primary.js". Error running Transform function inside template preprocessor: `````

<a id="531370f3"></a>
###
 - **[Error]** `````Error transforming model "W:\vf54-o-9953c818\raw-\n1vbh3i0.h3i\rawmodel\stable\api\overview\azure\Storage\Client.raw.json" generated from "docs-ref-autogen/overview/Storage/Client.yml" using "ManagedReference.html.primary.js". Error running Transform function inside template preprocessor: `````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C29%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201906291405322723-882%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f4UMEf7dxkOsIey8erxZ3jRTibfmJhw7%2F7j0HgCI30k%3D&st=2019-06-29T14%3A57%3A27Z&se=2019-07-30T15%3A02%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[d9a5fcf](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/pull/882/commits/d9a5fcf8105bec3322ba443bed076668bfeb4f41)_: 

:clock10: **Full build**: the average full build time is _71 min(s) 47 sec(s)_, this is based on the last _297_ build(s) for this repository.

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[d9a5fcf](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/pull/882/commits/d9a5fcf8105bec3322ba443bed076668bfeb4f41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/includes/java-aad-samples.md](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-conceptual/includes/java-aad-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/includes/java-aad-samples?view=azure-java-stable&branch=pr-en-us-882) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/includes/java-aad-samples?view=azure-java-preview&branch=pr-en-us-882) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/includes/java-aad-samples?view=azure-java-legacy&branch=pr-en-us-882) (azure-java-legacy) |
[docs-ref-conceptual/includes/java-container-samples.md](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-conceptual/includes/java-container-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/includes/java-container-samples?view=azure-java-stable&branch=pr-en-us-882) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/includes/java-container-samples?view=azure-java-preview&branch=pr-en-us-882) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/includes/java-container-samples?view=azure-java-legacy&branch=pr-en-us-882) (azure-java-legacy) |
[docs-ref-conceptual/includes/java-sql-samples.md](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-conceptual/includes/java-sql-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/includes/java-sql-samples?view=azure-java-stable&branch=pr-en-us-882) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/includes/java-sql-samples?view=azure-java-preview&branch=pr-en-us-882) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/includes/java-sql-samples?view=azure-java-legacy&branch=pr-en-us-882) (azure-java-legacy) |
[docs-ref-conceptual/jdk/java-jdk-docker-images.md](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-conceptual/jdk/java-jdk-docker-images.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/jdk/java-jdk-docker-images?view=azure-java-stable&branch=pr-en-us-882) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/jdk/java-jdk-docker-images?view=azure-java-preview&branch=pr-en-us-882) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/jdk/java-jdk-docker-images?view=azure-java-legacy&branch=pr-en-us-882) (azure-java-legacy) |
[docs-ref-conceptual/jdk/java-jdk-flight-recorder-and-mission-control.md](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-conceptual/jdk/java-jdk-flight-recorder-and-mission-control.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/jdk/java-jdk-flight-recorder-and-mission-control?view=azure-java-stable&branch=pr-en-us-882) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/jdk/java-jdk-flight-recorder-and-mission-control?view=azure-java-preview&branch=pr-en-us-882) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/jdk/java-jdk-flight-recorder-and-mission-control?view=azure-java-legacy&branch=pr-en-us-882) (azure-java-legacy) |
[docs-ref-conceptual/jdk/java-jdk-install.md](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-conceptual/jdk/java-jdk-install.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/jdk/java-jdk-install?view=azure-java-stable&branch=pr-en-us-882) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/jdk/java-jdk-install?view=azure-java-preview&branch=pr-en-us-882) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/jdk/java-jdk-install?view=azure-java-legacy&branch=pr-en-us-882) (azure-java-legacy) |
[docs-ref-conceptual/microprofile/index.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-conceptual/microprofile/index.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/microprofile/index?view=azure-java-stable&branch=pr-en-us-882) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/microprofile/index?view=azure-java-preview&branch=pr-en-us-882) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/microprofile/index?view=azure-java-legacy&branch=pr-en-us-882) (azure-java-legacy) |
[docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-from-container-registry-using-maven-plugin.md](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-from-container-registry-using-maven-plugin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-from-container-registry-using-maven-plugin?view=azure-java-stable&branch=pr-en-us-882) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-from-container-registry-using-maven-plugin?view=azure-java-preview&branch=pr-en-us-882) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-from-container-registry-using-maven-plugin?view=azure-java-legacy&branch=pr-en-us-882) (azure-java-legacy) |
[legacy/docs-ref-autogen/com.microsoft.azure.storage.table.yml](https://github.com/craigcaseyMSFT/azure-docs-sdk-java/blob/vcraic0627/legacy/docs-ref-autogen/com.microsoft.azure.storage.table.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/com.microsoft.azure.storage.table?view=azure-java-legacy&branch=pr-en-us-882) (azure-java-legacy) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C29%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201906291511393022-882%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ni6PJuXzjZ9scxQ7D1PhelClCYlwfZVOpixhNCDtnKQ%3D&st=2019-06-29T16%3A37%3A47Z&se=2019-07-30T16%3A42%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by craigcaseyMSFT** [comment]
@rloutlaw   - Hi, Robert. I believe you are the correct person to contact about merging PRs in this repo? If so, please merge this one when you have a chance. It corrects several issues that were flagged in a recent CATS error report.

Thanks for your help!

**Comment by craigcaseyMSFT** [comment]
closing due to migration effort going on in this area of the repo

**Pull request closed without merging**
