### PR TITLE
M31735: Missing link in URL list

### PR DESCRIPTION
**Pull request by v-maudel**
Hello, @rmcmurray,  
Translator has reported possible source content issue. 
Description: There is a missing URL for [Azure for Java Developers] (used at line 400)

Please review the comment tag added and reply with explanation if fix is needed or not. If you make related fix in another PR then share your PR number so we can confirm and close this PR.
Many thanks in advance.

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md](https://github.com/v-maudel/azure-docs-sdk-java/blob/patch-1/docs-ref-conceptual/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-stable&branch=pr-en-us-648) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-preview&branch=pr-en-us-648) (azure-java-preview) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C4%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201810041511537118-648%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5vhqMDUnqonmuTcKb%2F8%2BJKFm8Dmzl2YzYX42oXpbyTE%3D&st=2018-10-04T16%3A03%3A02Z&se=2018-11-04T16%3A08%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by brunoborges** [comment]
@rloutlaw can you take a look at this one, please?

**Comment by rloutlaw** [comment]
adding @rmcmurray to this PR for review

**Comment by v-makoud** [comment]
Hi @rmcmurray,

can you look into this?

Cc: @rloutlaw, @brunoborges

**Comment by v-makoud** [comment]
Hi @rmcmurray,

can you look into this?

Cc: @rloutlaw, @brunoborges

**Comment by brunoborges** [comment]
@v-makoud would you mind submitting a PR that fixes the problem?

**Comment by v-maudel** [comment]
Hi @brunoborges , we can't fix this issue due we don't know the right link . We only report this kind of issues but we aren't able to fix it. 

Regards.

**Comment by v-maudel** [comment]
Hi @brunoborges  , we can't fix this issue due we don't know the right link . We only report this kind of issues but we aren't able to fix it.

Cc: @rmcmurray, @rloutlaw, @mbaldwin
Regards.

**Comment by v-makoud** [comment]
Hi @brunoborges , we can't fix this issue due we don't know the right link . We only report this kind of issues but we aren't able to fix it.

Cc: @rmcmurray, @rloutlaw, @mbaldwin, @v-maudel
Regards.

**Comment by rmcmurray** [comment]
Thanks, @v-makoud - the missing link should point to the relative URL of /java/azure/, or <https://docs.microsoft.com/java/azure/> for the full URL.

Thanks again!

**Comment by v-maudel** [comment]
Thanks so much @rmcmurray It was added at line 406. If it is ok, please merge or sign off this PR. 
Regards. 

Cc: @brunoborges , @rloutlaw, @mbaldwin, @v-makoud 
Regards.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md](https://github.com/v-maudel/azure-docs-sdk-java/blob/patch-1/docs-ref-conceptual/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-stable&branch=pr-en-us-648) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-preview&branch=pr-en-us-648) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-legacy&branch=pr-en-us-648) (azure-java-legacy) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C6%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201812061413209922-648%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=R5T0pGw2ttmanzO7%2F5XaV%2BfW8MSuxHXMDDxjiIpxyTU%3D&st=2018-12-06T15%3A26%3A27Z&se=2019-01-06T15%3A31%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-makoud** [comment]
Thanks so much @rmcmurray It was added at line 406. If it is ok, please merge or sign off this PR.
Regards.

Cc: @brunoborges , @rloutlaw, @mbaldwin, @v-maudel 
Regards.

**Comment by v-makoud** [comment]
Thanks so much @rmcmurray It was added at line 406. If it is ok, please merge or sign off this PR.
Regards.

Cc: @brunoborges , @rloutlaw, @mbaldwin, @v-maudel
Regards.

**Comment by rmcmurray** [comment]
@v-makoud - this PR was held up by the broken build process, (which also prevented some other PRs from being built).

However, these URL changes have already been addressed in PR #743, so you can delete this PR.

**Comment by rmcmurray** [comment]
@v-makoud - this PR was held up by the broken build process, (which also prevented some other PRs from being built).

However, these URL changes have already been addressed in PR #743, so I will close this PR.

**Comment by v-maudel** [comment]
Thanks @rmcmurray , 
Although, The link we reported as missing is still missing in the article. 
image

In the upper line exist a reference to the *Azure for Java Developers* link but it is not present in the URL list from below. 

Could you please let us know the resolution? If needed we can create a new PR with the suggestion for your approval. 

regards.
Mauricio.

**Comment by v-maudel** [comment]
Thanks @rmcmurray , 
Although, The link we reported as missing is still missing in the article. 
image

In the upper line exist a reference to the *Azure for Java Developers* link but it is not present in the URL list from below. 

Could you please let us know the resolution? If needed we can create a new PR with the suggestion for your approval. 

regards.
Mauricio.

Cc: @brunoborges , @rloutlaw, @mbaldwin @v-makoud

**Comment by v-maudel** [comment]
New PR created here: https://github.com/Azure/azure-docs-sdk-java/pull/768

**Pull request closed without merging**
