### PR TITLE
Corrected Azure Cosmos DB DocumentDB API->SQL API

### PR DESCRIPTION
**Pull request by mimig1**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db.md](https://github.com/mimig1/azure-docs-sdk-java/blob/patch-3/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C2%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201804021912134593-403%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4eVezzpw4UNiu6G4sIEhOcfqlZ1b6yjCM0te9V%2BMyTU%3D&st=2018-04-02T19%3A36%3A01Z&se=2018-05-03T19%3A41%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mimig1** [comment]
@rloutlaw - Can you review & merge? Do these get staged?

**Comment by rloutlaw** [comment]
@mimig1 can you reopen this vs. a merge into the master (and not live) branch? I can't merge direct into live-that's our  ref pub team only.

**Comment by mimig1** [comment]
@rloutlaw - Will do.

**Comment by mimig1** [comment]
@rloutlaw - Created https://github.com/Azure/azure-docs-sdk-java/pull/406 to merge to master instead

**Pull request closed without merging**
