### PR TITLE
Checking in updated Spring AAD Starter article

### PR DESCRIPTION
**Pull request by rmcmurray**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/application-login.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/application-login.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-02.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-02.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-03.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-03.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-04.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-04.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-05.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-05.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-06.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-06.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-07.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-07.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-08.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-08.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-09.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-09.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-10.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-10.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-11.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-11.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-12.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-12.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-13.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-13.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/hello-world.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/hello-world.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-02.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-02.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-03.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-03.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-04.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-04.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C22%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201806221144373101-512%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=OLZ86Kcvblh09nVANmM9sKiaIEKzwkwhOn7HaEg5mQk%3D&st=2018-06-22T12%3A18%3A46Z&se=2018-07-23T12%3A23%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/application-login.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/application-login.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-02.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-02.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-03.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-03.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-04.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-04.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-05.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-05.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-06.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-06.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-07.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-07.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-08.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-08.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-09.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-09.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-10.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-10.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-11.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-11.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-12.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-12.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-13.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-13.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-14.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-14.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-15.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-15.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/hello-world.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/hello-world.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-02.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-02.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-03.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-03.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-04.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-04.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C26%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201806260450329936-512%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PPyqmKbDHWUpV2IHQMfPQqQ26nlR8%2BubeU5SWr%2FT0t8%3D&st=2018-06-26T05%3A26%3A25Z&se=2018-07-27T05%3A31%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/application-login.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/application-login.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-02.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-02.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-03.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-03.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-04.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-04.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-05.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-05.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-06.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-06.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-07.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-07.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-08.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-08.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-09.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-09.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-10.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-10.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-11.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-11.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-12.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-12.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-13.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-13.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-14.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-14.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-15.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-15.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/hello-world.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/hello-world.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-02.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-02.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-03.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-03.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-04.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-04.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C26%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201806260458157276-512%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fRUb2kFalYagtO%2F9HnQGXZtUS%2Bao%2Bovhx5EbpiEFG4E%3D&st=2018-06-26T06%3A05%3A09Z&se=2018-07-27T06%3A10%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/application-login.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/application-login.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/build-application.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/build-application.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-02.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-02.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-03.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-03.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-04.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-04.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-05.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-05.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-06.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-06.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-07.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-07.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-08.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-08.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-09.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-09.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-10.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-10.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-11.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-11.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-12.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-12.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-13.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-13.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-14.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-14.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-15.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-15.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/hello-world.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/hello-world.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/logged-in-user.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/logged-in-user.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-02.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-02.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-03.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-03.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-04.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180620/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/security-04.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C26%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201806261457146833-512%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qCC3NFXwXk7AOK%2FXaD2UUw7iC8px%2Bx0b8kylE6CnRPA%3D&st=2018-06-26T15%3A32%3A07Z&se=2018-07-27T15%3A37%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rmcmurray** [comment]
#sign-off

**Pull request merged**
