### PR TITLE
Update network toc to Track 2

### PR DESCRIPTION
**Pull request by nickzhums**

### CODE REVIEW

**Review by scbedd — APPROVED** [review]

**Comment by scbedd** [comment]
@nickzhums you're g2g!

**Comment by scbedd** [comment]
@nickzhums I noticed too late that this update was against `master`. Please create this PR again to `main`! I'll merge that too.

**Review by weidongxu-microsoft — COMMENTED** [review]
LGTM as Java SDK owner.

**Comment by nickzhums** [comment]
@scbedd np, i created another PR against main

**Pull request merged**
