### PR TITLE
Create mixed-reality.md

### PR DESCRIPTION
**Pull request by XiangyuL-Microsoft**
Create the overview page of reference documentation for the Java client libraries for Azure Mixed Reality Resource Management

### CODE REVIEW

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[0cd15f4](https://github.com/XiangyuL-Microsoft/azure-docs-sdk-java/pull/815/commits/0cd15f451a9afa2bd3712daa974c2e4f315296d0)_: 

:clock10: **Full build**: the average full build time is _70 min(s) 3 sec(s)_, this is based on the last _205_ build(s) for this repository.

 :warning: **This is a FULL build** due to the incremental build being disabled in configuration file (.openpublishing.publish.config.json in 'live' branch). For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[0cd15f4](https://github.com/XiangyuL-Microsoft/azure-docs-sdk-java/pull/815/commits/0cd15f451a9afa2bd3712daa974c2e4f315296d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/mixed-reality.md](https://github.com/XiangyuL-Microsoft/azure-docs-sdk-java/blob/patch-1/docs-ref-services/mixed-reality.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/mixed-reality?view=azure-java-stable&branch=pr-en-us-815) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/mixed-reality?view=azure-java-preview&branch=pr-en-us-815) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/mixed-reality?view=azure-java-legacy&branch=pr-en-us-815) (azure-java-legacy) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C16%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201904162209292983-815%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=R47a4ARpZpYN6Rcpbw3rI3cMoF7AO75m9eFhBMfGINk%3D&st=2019-04-16T23%3A21%3A58Z&se=2019-05-17T23%3A26%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by brunoborges** [comment]
@XiangyuL-Microsoft  the `groupId` should be `com.microsoft.azure` like all other libraries, and the `artifactId` should then be related to Azure Mixed Reality.

// @selvasingh @JonathanGiles

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[bdcdfb1](https://github.com/XiangyuL-Microsoft/azure-docs-sdk-java/pull/815/commits/bdcdfb19e7cabd4582fc1b066a7791349d33ff36)_: 

:clock10: **Pending**: waiting for processors ([9](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by XiangyuL-Microsoft** [comment]
> Republish the artifact under proper groupId and artifactId.

I have 0 knowledge on Maven/POM. It seems I copied something by mistake. The POM of the Java SDK is [this](https://search.maven.org/classic/remotecontent?filepath=com/microsoft/azure/mixedreality/v2019_02_28_preview/azure-mgmt-mixedreality/1.0.0-beta/azure-mgmt-mixedreality-1.0.0-beta.pom). 

Thanks.

@brunoborges

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[bdcdfb1](https://github.com/XiangyuL-Microsoft/azure-docs-sdk-java/pull/815/commits/bdcdfb19e7cabd4582fc1b066a7791349d33ff36)_: 

:clock10: **Full build**: the average full build time is _70 min(s) 3 sec(s)_, this is based on the last _207_ build(s) for this repository.

 :warning: **This is a FULL build** due to the incremental build being disabled in configuration file (.openpublishing.publish.config.json in 'live' branch). For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by brunoborges** [comment]
Where is the source code of the Maven project and who is the owner?

The groupId needs to be fixed and the artifact needs to be republished.

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[bdcdfb1](https://github.com/XiangyuL-Microsoft/azure-docs-sdk-java/pull/815/commits/bdcdfb19e7cabd4582fc1b066a7791349d33ff36)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/mixed-reality.md](https://github.com/XiangyuL-Microsoft/azure-docs-sdk-java/blob/patch-1/docs-ref-services/mixed-reality.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/mixed-reality?view=azure-java-stable&branch=pr-en-us-815) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/mixed-reality?view=azure-java-preview&branch=pr-en-us-815) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/mixed-reality?view=azure-java-legacy&branch=pr-en-us-815) (azure-java-legacy) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C17%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201904170105295233-815%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XekOmVfWp%2B3OKCkFLHmmmQRSSjwvfFi174Yfb%2BrMCQ0%3D&st=2019-04-17T02%3A20%3A04Z&se=2019-05-18T02%3A25%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by anuchandy** [comment]
@brunoborges - today all AutoGenerated (not Fluent) Management/ARM SDKs has api-version in the groupId, this was designed so to enable multi-api-version.

We are reevaluating the versioning story as part of our next codegen work that is in progress.

@lmazuel @jianghaolu

**Comment by brunoborges** [comment]
@anuchandy where does it say that all autogenerated SDKs for Java must have version as part of the groupId?

The version should go to the <version> element, or at most, major versions may go into the <artifactId>.

Where is this defined?

// @JonathanGiles @selvasingh

**Comment by sima-zhu** [comment]
@XiangyuL-Microsoft Do we still need this PR? Could you provide some context on this?

**Comment by sima-zhu** [comment]
I will close the PR if no response before the end of next week. Thanks! :)

**Pull request closed without merging**
