### PR TITLE
C54248: Closing code box

### PR DESCRIPTION
**Pull request by v-makoud**
Hello, @rmcmurray,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.
Many thanks in advance.

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md](https://github.com/v-makoud/azure-docs-sdk-java/blob/patch-4/docs-ref-conceptual/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-stable&branch=pr-en-us-721) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-preview&branch=pr-en-us-721) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-legacy&branch=pr-en-us-721) (azure-java-legacy) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C5%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201812050838502374-721%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Bx9GEPCqQMDSP1Efjc3IN%2Bxx7l6HMEYN4uUAHdKi4Kc%3D&st=2018-12-05T09%3A49%3A06Z&se=2019-01-05T09%3A54%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rmcmurray** [comment]
This change looks great to me - #sign-off.

**Comment by v-makoud** [comment]
@rmcmurray the PR didnt #sign-off could you please try again, or ask someone who can.

**Comment by rmcmurray** [comment]
#sign-off

**Pull request merged**
