### PR TITLE
Update hdinsight.md

### PR DESCRIPTION
**Pull request by tylerfox**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[be5c086](https://github.com/tylerfox/azure-docs-sdk-java/pull/789/commits/be5c0866dc7304fb972688ebb105bd419f7a211f)_: 

:clock10: **Full build**: the average full build time is _69 min(s) 43 sec(s)_, this is based on the last _157_ build(s) for this repository.

 :warning: **This is a FULL build** due to the incremental build being disabled in configuration file (.openpublishing.publish.config.json in 'live' branch). For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[be5c086](https://github.com/tylerfox/azure-docs-sdk-java/pull/789/commits/be5c0866dc7304fb972688ebb105bd419f7a211f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/hdinsight.md](https://github.com/tylerfox/azure-docs-sdk-java/blob/patch-1/docs-ref-services/hdinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/hdinsight?view=azure-java-stable&branch=pr-en-us-789) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/hdinsight?view=azure-java-preview&branch=pr-en-us-789) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/hdinsight?view=azure-java-legacy&branch=pr-en-us-789) (azure-java-legacy) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C18%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201903182141391173-789%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Pj6a%2B%2BvWAMkp5Kk5M98FEr4PPCWb8bWIJzkN67GEf4E%3D&st=2019-03-18T22%3A49%3A41Z&se=2019-04-18T22%3A54%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[be5c086](https://github.com/tylerfox/azure-docs-sdk-java/pull/789/commits/be5c0866dc7304fb972688ebb105bd419f7a211f)_: 

:clock10: **Full build**: the average full build time is _69 min(s) 42 sec(s)_, this is based on the last _158_ build(s) for this repository.

 :warning: **This is a FULL build** due to the incremental build being disabled in configuration file (.openpublishing.publish.config.json in 'live' branch). For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[be5c086](https://github.com/tylerfox/azure-docs-sdk-java/pull/789/commits/be5c0866dc7304fb972688ebb105bd419f7a211f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/hdinsight.md](https://github.com/tylerfox/azure-docs-sdk-java/blob/patch-1/docs-ref-services/hdinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/hdinsight?view=azure-java-stable&branch=pr-en-us-789) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/hdinsight?view=azure-java-preview&branch=pr-en-us-789) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/hdinsight?view=azure-java-legacy&branch=pr-en-us-789) (azure-java-legacy) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C19%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201903182143071128-789%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=AY7MhpouNHp0UGhqHgFFHV3yVEd4POX2QuyBoELbQAs%3D&st=2019-03-19T00%3A06%3A51Z&se=2019-04-19T00%3A11%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by tylerfox** [comment]
#sign-off

**Pull request merged**
