### PR TITLE
Update sql.md

### PR DESCRIPTION
**Pull request by CarlRabeler**

### CODE REVIEW

**Comment by CarlRabeler** [comment]
@rloutlaw @erickson-doug trying to fix metadata, but apparently this is not the way...is this file auto-generated?

**Comment by erickson-doug** [comment]
you hafta set it in the docfx.json

--
Doug Erickson (douge) -- 425 273 1304


________________________________

**Comment by CarlRabeler** [comment]
Looking at the docfx.json file – not obvious how to fix.

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[c43dd27](https://github.com/CarlRabeler/azure-docs-sdk-java/pull/726/commits/c43dd2764482c365c389c49b5bd371b572d3104a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/sql.md](https://github.com/CarlRabeler/azure-docs-sdk-java/blob/patch-1/docs-ref-services/sql.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/sql?view=azure-java-stable&branch=pr-en-us-726) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/sql?view=azure-java-preview&branch=pr-en-us-726) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/sql?view=azure-java-legacy&branch=pr-en-us-726) (azure-java-legacy) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C11%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201812111848084877-726%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BJ8T7QQT6CTVgDevXsx7wCdzhuibUNE2x4k3i56qsdM%3D&st=2018-12-11T19%3A57%3A01Z&se=2019-01-11T20%3A02%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
