### PR TITLE
cut off dependency tag

### PR DESCRIPTION
**Pull request by tylerfox**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/hdinsight.md](https://github.com/tylerfox/azure-docs-sdk-java/blob/smoke-test/docs-ref-services/hdinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/hdinsight?view=azure-java-stable&branch=pr-en-us-632) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/hdinsight?view=azure-java-preview&branch=pr-en-us-632) (azure-java-preview) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C21%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201809202345401435-632%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2FJ4gR1S8cA0UWS9C%2Fny2L4o9A8JWAqaYCAzI95NJUXw%3D&st=2018-09-21T00%3A41%3A12Z&se=2018-10-22T00%3A46%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by brunoborges** [comment]
Is really the intention to submit this to `smoke-test` branch?

**Comment by tylerfox** [comment]
> Is really the intention to submit this to `smoke-test` branch?

Yeah, when I made this PR, my previous commits hadn't been merged into master yet. Now that they have, should I close this and make a new PR to master or do you want to merge this to master?

**Comment by brunoborges** [comment]
All good.

**Comment by tylerfox** [comment]
Thanks

**Pull request merged**
