### PR TITLE
Update cosmosdb-spring-boot-starter-readme.md

### PR DESCRIPTION
**Pull request by SnehaGunda**

### CODE REVIEW

**Comment by SnehaGunda** [comment]
#sign-off

**Comment by sima-zhu** [comment]
Could you please switch the target branch to smoke-test? We will be responsible to merge smoke-test to master. 
Thanks!

**Comment by sima-zhu** [comment]
@SnehaGunda Do we still need this PR? If so, could you provide some context on this? I will close the PR if I do not get any response before the end of next week. Thanks!

**Comment by SnehaGunda** [comment]
@sima-zhu Yes this PR fixes the ms.service metadata. It's not right for Comsos DB it should be cosmos-db. Please merge this PR.

**Pull request merged**
