### PR TITLE
Add config step in the tutorial to make the tutorial more straightforward 

### PR DESCRIPTION
**Pull request by andxu**
Signed-off-by: andxu <andxu@microsoft.com>

### CODE REVIEW

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[345a135](https://github.com/andxu/azure-docs-sdk-java/pull/861/commits/345a135f8e53b838e13a288856b2ec46d3a0ee07)_: 

:clock10: **Full build**: the average full build time is _71 min(s) 18 sec(s)_, this is based on the last _270_ build(s) for this repository.

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[345a135](https://github.com/andxu/azure-docs-sdk-java/pull/861/commits/345a135f8e53b838e13a288856b2ec46d3a0ee07)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md](https://github.com/andxu/azure-docs-sdk-java/blob/andxu_springboot_maven/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable&branch=pr-en-us-861) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-preview&branch=pr-en-us-861) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-legacy&branch=pr-en-us-861) (azure-java-legacy) |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-with-maven-plugin/AP01.png](https://github.com/andxu/azure-docs-sdk-java/blob/andxu_springboot_maven/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-with-maven-plugin/AP01.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-legacy&branch=pr-en-us-861) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-preview&branch=pr-en-us-861) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable&branch=pr-en-us-861) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-with-maven-plugin/AP02.png](https://github.com/andxu/azure-docs-sdk-java/blob/andxu_springboot_maven/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-with-maven-plugin/AP02.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-legacy&branch=pr-en-us-861) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-preview&branch=pr-en-us-861) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable&branch=pr-en-us-861) (azure-java-stable) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C29%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201905290153038261-861%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YSU4oebzK5K5kGCnag4pxIijMTMmdKPMK3d2sr2TFfs%3D&st=2019-05-29T03%3A05%3A53Z&se=2019-06-29T03%3A10%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by andxu** [comment]
#signoff

**Comment by brunoborges** [comment]
I see what you did here @andxu! :-D 

Well done mate.

**Pull request merged**
