### PR TITLE
Updating AAD and CA store articles

### PR DESCRIPTION
**Pull request by rmcmurray**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/java-sdk-add-certificate-ca-store.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/java-sdk-add-certificate-ca-store.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-14.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-14.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-16.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-16.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-17.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-17.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-18.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-18.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-19.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-19.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-20.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-20.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-21.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-21.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-22.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-22.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/update-password.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/update-password.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C4%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201807040914127049-526%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gP0%2BcYHcryGjHnQURfI1cjaARx3IEOd6Z6KsHbrjXtE%3D&st=2018-07-04T09%3A44%3A15Z&se=2018-08-04T09%3A49%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/java-sdk-add-certificate-ca-store.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/java-sdk-add-certificate-ca-store.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-14.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-14.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-16.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-16.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-17.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-17.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-18.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-18.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-19.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-19.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-20.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-20.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-21.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-21.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-22.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-22.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/update-password.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/update-password.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C4%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201807041006222098-526%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=w2GYUIhyfJkmiFVhPwIN0dTPqOMyOYNsuLcSjZ8pyV8%3D&st=2018-07-04T10%3A35%3A27Z&se=2018-08-04T10%3A40%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rmcmurray** [comment]
#sign-off

**Comment by rmcmurray** [comment]
Sorry, just caught a typo - #hold-off.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/java-sdk-add-certificate-ca-store.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/java-sdk-add-certificate-ca-store.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-14.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-14.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-16.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-16.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-17.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-17.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-18.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-18.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-19.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-19.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-20.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-20.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-21.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-21.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-22.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/directory-22.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/update-password.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180703/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory/update-password.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C4%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201807041510073841-526%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VsoYRSZIGQfKzwX4kE6wrawfO3pCe0WOdiPiWApxfz0%3D&st=2018-07-04T15%3A40%3A16Z&se=2018-08-04T15%3A45%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rmcmurray** [comment]
#sign-off

**Pull request merged**
