### PR TITLE
Exclude the attestation service implementation.

### PR DESCRIPTION
**Pull request by LarryOsterman**

### CODE REVIEW

**Comment by pallavit** [comment]
@danieljurek please let us know if this change is sufficient to exclude the documentation for implementation package.

**Review by pallavit — APPROVED** [review]
LGTM

**Comment by LarryOsterman** [comment]
Ping @danieljurek ,  it would be lovely if you could take a peek at this to confirm that I didn't break anything.

**Comment by danieljurek** [comment]
@sima-zhu can help answer questions here. 

@LarryOsterman -- Unfortunately at this time there isn't an easy way to validate that docs CI will succeed given changes that are proposed in a fork. You should already have permissions to push to a branch in this repository. Once that's done we can perform a CI build and check the outputs. Please name your branch something like `LarryOsterman/ExcludeAttestationImplementation` to make it easier to clean up in the future if it gets left behind after merging.

**Comment by LarryOsterman** [comment]
> @sima-zhu can help answer questions here.
> 
> @LarryOsterman -- Unfortunately at this time there isn't an easy way to validate that docs CI will succeed given changes that are proposed in a fork. You should already have permissions to push to a branch in this repository. Once that's done we can perform a CI build and check the outputs. Please name your branch something like `LarryOsterman/ExcludeAttestationImplementation` to make it easier to clean up in the future if it gets left behind after merging.

Thank you Daniel. We just wanted to confirm that this looked like the changes were "reasonable". We'll see what happens after the next documentation pass runs.

**Comment by sima-zhu** [comment]
We have a step to hide the implementation package, so you don't need to worry about the exclusion.

**Comment by LarryOsterman** [comment]
If there's a step to hide the implementation package, any ideas why that step isn't working for the Attestation service? The reason we started down the exclusion path is that the implementation package is being published.

**Comment by sima-zhu** [comment]
https://review.docs.microsoft.com/en-us/java/api/overview/azure/attestation?view=azure-java-stable&branch=main

It is resolved now. We have different strategies to make sure implementation not included.

**Pull request merged**
