### PR TITLE
Restore known issues section to overview page

### PR DESCRIPTION
**Pull request by pauljewellmsft**

### CODE REVIEW

**Comment by pauljewellmsft** [comment]
@tamram Could you approve this PR, please? These are the same changes we made last month, but apparently they got wiped out by the auto-generated content.

**Comment by normesta** [comment]
Hi @pauljewellmsft is there something in specific you believe requires my (or Tamra's) approval or are you just seeking a second pair of eyes? I would assume the SME for the area (dev / PM etc) would make the better approver for this sort of content. Question - you mentioned that this content was overwritten by some sort of automation. Was this a one-off thing or do you have some way of assuring that your content won't be overwritten again? Content being overwritten indicates that direct edits to this content is less optimal than edits to whatever source is performing the overwrite. Also, it looks like you have some validation issues that should be resolved - absolute links and the removal of version info in at the end of URLs. Both can be easily resolved. Let me know if you would like pointers to information in our style guide for how to resolve those. Cheers!

**Comment by tamram** [comment]
@pauljewellmsft - I didn't realize anything on this page was auto-generated. Do you know where it's coming from?

**Comment by tamram** [comment]
@pauljewellmsft - can you fix the validation errors? then i'll approve.

**Comment by pauljewellmsft** [comment]
Thanks @tamram - should be all set now. Once approved, I'll try to merge if I'm able.

**Comment by tamram** [comment]
@pauljewellmsft - can you change the ms.author field to yourself?

**Comment by pauljewellmsft** [comment]
@tamram Sorry about that - I wasn't sure if my name should be on a doc in this repo, but it's updated now. Thanks again for your help!

**Comment by tamram** [comment]
> I wasn't sure if my name should be on a doc in this repo, but it's updated now. Thanks again for your help!

Yes, it's completely fine. We don't currently have another owner.

**Review by tamram — APPROVED** [review]

**Comment by tamram** [comment]
@pauljewellmsft - let me know if you can't merge.

**Pull request merged**
