### PR TITLE
Simplifying Azure Java docs TOC

### PR DESCRIPTION
**Pull request by JonathanGiles**
Removing duplicated content (the Maven / IntelliJ / Eclipse getting started docs were largely duplicated). Added relevant info for IntelliJ and Eclipse into the 'maven' page, and promoted it to the top of the 'Java Quickstarts' section in a 'Getting Started' page. Removed the 'Azure libraries for Java' section entirely, as well as the two eclipse / intelliJ get-started pages.

Also, collapsed a few quick starts under a 'Database' section header.

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/eclipse/java-sdk-azure-get-started-eclipse.md](https://github.com/JonathanGiles/azure-docs-sdk-java/blob/master/docs-ref-conceptual/eclipse/java-sdk-azure-get-started-eclipse.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/intellij/java-sdk-azure-get-started-intellij.md](https://github.com/JonathanGiles/azure-docs-sdk-java/blob/master/docs-ref-conceptual/intellij/java-sdk-azure-get-started-intellij.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/java-sdk-azure-get-started.md](https://github.com/JonathanGiles/azure-docs-sdk-java/blob/master/docs-ref-conceptual/java-sdk-azure-get-started.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/toc.yml](https://github.com/JonathanGiles/azure-docs-sdk-java/blob/master/docs-ref-conceptual/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C7%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201808070027340004-559%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BP0M08I483HaYSJ%2BOlvjWjsRbP4KxhRXaF52SAMQrOo%3D&st=2018-08-07T01%3A02%3A13Z&se=2018-09-07T01%3A07%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by brunoborges** [comment]
@dend any chance we can get a preview of this ?

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/eclipse/java-sdk-azure-get-started-eclipse.md](https://github.com/JonathanGiles/azure-docs-sdk-java/blob/master/docs-ref-conceptual/eclipse/java-sdk-azure-get-started-eclipse.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/intellij/java-sdk-azure-get-started-intellij.md](https://github.com/JonathanGiles/azure-docs-sdk-java/blob/master/docs-ref-conceptual/intellij/java-sdk-azure-get-started-intellij.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/java-sdk-azure-get-started.md](https://github.com/JonathanGiles/azure-docs-sdk-java/blob/master/docs-ref-conceptual/java-sdk-azure-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/java-sdk-azure-get-started?view=azure-java-stable&branch=pr-en-us-559) (azure-java-stable) |
[docs-ref-conceptual/toc.yml](https://github.com/JonathanGiles/azure-docs-sdk-java/blob/master/docs-ref-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/java-sdk-azure-get-started?view=azure-java-stable&branch=pr-en-us-559) (azure-java-stable) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C7%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201808071758166221-559%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cYz%2BjZ8e8vtD3DpYsO8b2PQt5KtqBF99ciGAKjcErwM%3D&st=2018-08-07T18%3A37%3A38Z&se=2018-09-07T18%3A42%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by brunoborges** [comment]
@rloutlaw I have some enhancements to do after this PR, but this is in the right direction anyway, so my recommendation is to merge.

**Comment by rloutlaw** [comment]
Thanks @JonathanGiles

**Comment by JonathanGiles** [comment]
What is the timeframe for seeing this live or in a sandbox?

**Pull request merged**
