### PR TITLE
1387770: Changed link for "Java Tools for Visual Studio Team Services"

### PR DESCRIPTION
**Pull request by rmcmurray**
This is an attempted replacement of PR #722

### CODE REVIEW

**Comment by rmcmurray** [comment]
Adding @DennisLee-DennisLee to the discussion

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[449a9e4](https://github.com/rmcmurray/azure-docs-sdk-java/pull/732/commits/449a9e4bcbc8dd4a21eda49624be5b607bb2d41b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/eclipse/azure-toolkit-for-eclipse.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20181211/docs-ref-conceptual/eclipse/azure-toolkit-for-eclipse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/eclipse/azure-toolkit-for-eclipse?view=azure-java-stable&branch=pr-en-us-732) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/eclipse/azure-toolkit-for-eclipse?view=azure-java-preview&branch=pr-en-us-732) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/eclipse/azure-toolkit-for-eclipse?view=azure-java-legacy&branch=pr-en-us-732) (azure-java-legacy) |
[docs-ref-conceptual/includes/azure-toolkit-for-eclipse-additional-resources.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20181211/docs-ref-conceptual/includes/azure-toolkit-for-eclipse-additional-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/includes/azure-toolkit-for-eclipse-additional-resources?view=azure-java-stable&branch=pr-en-us-732) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/includes/azure-toolkit-for-eclipse-additional-resources?view=azure-java-preview&branch=pr-en-us-732) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/includes/azure-toolkit-for-eclipse-additional-resources?view=azure-java-legacy&branch=pr-en-us-732) (azure-java-legacy) |
[docs-ref-conceptual/includes/azure-toolkit-for-intellij-additional-resources.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20181211/docs-ref-conceptual/includes/azure-toolkit-for-intellij-additional-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/includes/azure-toolkit-for-intellij-additional-resources?view=azure-java-stable&branch=pr-en-us-732) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/includes/azure-toolkit-for-intellij-additional-resources?view=azure-java-preview&branch=pr-en-us-732) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/includes/azure-toolkit-for-intellij-additional-resources?view=azure-java-legacy&branch=pr-en-us-732) (azure-java-legacy) |
[docs-ref-conceptual/intellij/azure-toolkit-for-intellij.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20181211/docs-ref-conceptual/intellij/azure-toolkit-for-intellij.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/intellij/azure-toolkit-for-intellij?view=azure-java-stable&branch=pr-en-us-732) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/intellij/azure-toolkit-for-intellij?view=azure-java-preview&branch=pr-en-us-732) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/intellij/azure-toolkit-for-intellij?view=azure-java-legacy&branch=pr-en-us-732) (azure-java-legacy) |
[docs-ref-conceptual/spring-framework/configure-spring-boot-initializer-java-app-with-redis-cache.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20181211/docs-ref-conceptual/spring-framework/configure-spring-boot-initializer-java-app-with-redis-cache.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-initializer-java-app-with-redis-cache?view=azure-java-stable&branch=pr-en-us-732) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-initializer-java-app-with-redis-cache?view=azure-java-preview&branch=pr-en-us-732) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-initializer-java-app-with-redis-cache?view=azure-java-legacy&branch=pr-en-us-732) (azure-java-legacy) |
[docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20181211/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-on-kubernetes?view=azure-java-stable&branch=pr-en-us-732) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-on-kubernetes?view=azure-java-preview&branch=pr-en-us-732) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-on-kubernetes?view=azure-java-legacy&branch=pr-en-us-732) (azure-java-legacy) |
[docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-on-linux.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20181211/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-on-linux.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-on-linux?view=azure-java-stable&branch=pr-en-us-732) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-on-linux?view=azure-java-preview&branch=pr-en-us-732) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-on-linux?view=azure-java-legacy&branch=pr-en-us-732) (azure-java-legacy) |
[docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-using-fabric8-maven-plugin.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20181211/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-using-fabric8-maven-plugin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-using-fabric8-maven-plugin?view=azure-java-stable&branch=pr-en-us-732) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-using-fabric8-maven-plugin?view=azure-java-preview&branch=pr-en-us-732) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-using-fabric8-maven-plugin?view=azure-java-legacy&branch=pr-en-us-732) (azure-java-legacy) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C12%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201812121747593395-732%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3L04kMG%2BtcHBW%2BdveyYC5L9nIgpSKDPVgRE0uhsp0As%3D&st=2018-12-12T18%3A52%3A23Z&se=2019-01-12T18%3A57%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[3e3abe9](https://github.com/rmcmurray/azure-docs-sdk-java/pull/732/commits/3e3abe91e5dd3ca7c24752cc100338b79f3a589c)_: 

:clock10: **Preparing**: average preparing time is _5 min(s) 54 sec(s)_

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[3e3abe9](https://github.com/rmcmurray/azure-docs-sdk-java/pull/732/commits/3e3abe91e5dd3ca7c24752cc100338b79f3a589c)_: 

:clock10: **Full build**: average full build time is _68 min(s) 18 sec(s)_ [calculated from last _71_ build(s)]

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Pull request merged**
