### PR TITLE
[bulk]Validation: cosmos-encryption metadata and absolute links

### PR DESCRIPTION
**Pull request by v-emilypr**

### CODE REVIEW

**Comment by v-emilypr** [comment]
**Global effort to fix build validation errors**

@kushagraThapar 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

**Comment by kushagraThapar** [comment]
@v-emilypr - I looked at the PR, but I don't think your changes will fix these issues. Reason being, this is currently the latest version of cosmos-encryption README.md file - which is originally located here - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-encryption/README.md

As soon as we release another version of this library, the documentation will automatically get updated with this README.md contents, and hence you will again see the same issues. 

Can I help with updating the original README.md file ? Please take a look, thanks!

**Comment by v-andreaco** [comment]
@kushagraThapar 

This article is throwing these validation warnings and suggestions:

[ms-prod-and-service](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-prod-and-service?branch=main)
[title-missing](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/title-missing?branch=main)
[ms-prod-technology-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)
[ms-service-subservice-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-service-subservice-invalid?branch=main)
[docs-link-absolute](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/docs-link-absolute?branch=main)

If you could fix those issues in the original readme, that would be enormously helpful.

**Comment by kushagraThapar** [comment]
@v-andreaco - will take a look at this soon, thanks!

**Comment by kushagraThapar** [comment]
Actually on another thought, I see this readme.md file is very similar to what we have in other modules as well - like this one - https://review.docs.microsoft.com/en-us/java/api/overview/azure/cosmos-readme?view=azure-java-stable&branch=pr-en-us-2213

Which has same links as this file, so not sure why only this one is being flagged. 
cc @v-emilypr cc @v-andreaco

**Comment by v-andreaco** [comment]
@kushagraThapar 

In order not to overwhelm reviewers, we sometimes break up our changes into multiple PRs by folder. To find all of the issues flagged for this repo, you can check out the [latest build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C5de83821-f44b-0e93-473e-c19393f102fe%5CCommit%5C202204210725120284-main%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T08%3A54%3A11Z&sr=b&sp=r&sig=1Xw%2BpB0TBjlNjIrM8kQZ8kv71w64vb8KCkihjF7pNY4%3D). It'll show you all of the files throwing warnings or suggestions.

If there are other PRs that make changes to README files, should we also leave them alone?

**Comment by kushagraThapar** [comment]
@v-andreaco - makes sense splitting the PRs. Also, adding title and description makes sense. 
However, with links - I don't understand how can we use relative links that you have fixed in this PR - since both the documents live in different repositories. 

This is the file that we are fixing it here - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-encryption/README.md

Can you please help me make changes to this file, so that we fix it once and for all :)

I can also do similar changes then to our different module readme files in this parent module - https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cosmos

**Comment by v-andreaco** [comment]
Thanks! Yes, we can do that. @v-emilypr , could you make these same link edits in the source file? 
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-encryption/README.md

@kushagraThapar 
As long as links are pointing to other content on docs.microsoft.com, they can be relative, even if they're going to another repo. Detailed in [Links to articles in other repos or docsets](https://review.docs.microsoft.com/help/contribute/links-how-to?branch=main#links-to-articles-in-other-repos-or-docsets). 

Also, it looks like the metadata changes here are still valid? I'm not seeing any metadata in the source, so I assume those values won't be overwritten? Can this PR be merged? Please let me know if I'm misunderstanding something. :)

**Comment by v-emilypr** [comment]
Link edits to source file can be found in the following PR: 

https://github.com/Azure/azure-sdk-for-java/pull/28469

**Pull request closed without merging**
