### PR TITLE
Fix version number and method casing.

### PR DESCRIPTION
**Pull request by dhaval24**
As the title suggest.

### CODE REVIEW

**Comment by dhaval24** [comment]
@mrbullwinkle would you please approve this doc changes? It's just small fix.

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[0aef314](https://github.com/dhaval24/azure-docs-sdk-java/pull/817/commits/0aef314f8f243d13cf28b213f788df0595cc88f7)_: 

:clock10: **Full build**: the average full build time is _70 min(s) 8 sec(s)_, this is based on the last _209_ build(s) for this repository.

 :warning: **This is a FULL build** due to the incremental build being disabled in configuration file (.openpublishing.publish.config.json in 'live' branch). For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by mrbullwinkle** [comment]
Once the above build checks finish we should be able to merge this one.

**Comment by openpublishbuild** [comment]
Docs Build status updates of commit _[0aef314](https://github.com/dhaval24/azure-docs-sdk-java/pull/817/commits/0aef314f8f243d13cf28b213f788df0595cc88f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/appinsights.md](https://github.com/dhaval24/azure-docs-sdk-java/blob/patch-1/docs-ref-services/appinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/appinsights?view=azure-java-stable&branch=pr-en-us-817) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/appinsights?view=azure-java-preview&branch=pr-en-us-817) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/appinsights?view=azure-java-legacy&branch=pr-en-us-817) (azure-java-legacy) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C18%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201904181812027020-817%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5456XJMEUiFh%2FuTSOyFdXI5jpBNc06hKMN9dwtj1u9E%3D&st=2019-04-18T19%3A23%3A29Z&se=2019-05-19T19%3A28%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
