### PR TITLE
Updating Spring Cosmos DB article

### PR DESCRIPTION
**Pull request by rmcmurray**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180810/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db?view=azure-java-stable&branch=pr-en-us-573) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ05.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180810/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ05.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db?view=azure-java-stable&branch=pr-en-us-573) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/PM02.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180810/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/PM02.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db?view=azure-java-stable&branch=pr-en-us-573) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/SI01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180810/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/SI01.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db?view=azure-java-stable&branch=pr-en-us-573) (azure-java-stable) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C15%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201808150507518511-573%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=E7j8qZpX1k69Rle6%2FMGYb7wpMObkUg20JFjbU4kqXXg%3D&st=2018-08-15T07%3A03%3A33Z&se=2018-09-15T07%3A08%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rmcmurray** [comment]
@SnehaGunda - @rloutlaw suggested that you might want to take a look at this article. Thanks!

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180810/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db?view=azure-java-stable&branch=pr-en-us-573) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180810/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ01.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db?view=azure-java-stable&branch=pr-en-us-573) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ02.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180810/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ02.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db?view=azure-java-stable&branch=pr-en-us-573) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ03.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180810/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ03.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db?view=azure-java-stable&branch=pr-en-us-573) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ05.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180810/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ05.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db?view=azure-java-stable&branch=pr-en-us-573) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/PM02.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180810/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/PM02.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db?view=azure-java-stable&branch=pr-en-us-573) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/SI01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180810/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/SI01.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db?view=azure-java-stable&branch=pr-en-us-573) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/SI03.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180810/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/SI03.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db?view=azure-java-stable&branch=pr-en-us-573) (azure-java-stable) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C15%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201808151300398600-573%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UNr%2FNuQjRgARz5yioiB7oPTr8IxdMFiLZ9Rx6K%2FGzxE%3D&st=2018-08-15T16%3A33%3A25Z&se=2018-09-15T16%3A38%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rmcmurray** [comment]
#sign-off

**Comment by SnehaGunda** [comment]
@rmcmurray thanks for tagging me, scanned through the doc, the changes look good to me, I didn't had a chance to test it yet, will do when I get a chance.

**Pull request merged**
