### PR TITLE
C37980: Adding breaklines to avoid broken content

### PR DESCRIPTION
**Pull request by v-maudel**
Hi @rmcmurray
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.  
Description: Erase extra breaklines and spaces in table in order to avoid broken table in both source and localized files.
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.
Many thanks in advance.

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-data-gremlin-java-app-with-cosmos-db.md](https://github.com/v-maudel/azure-docs-sdk-java/blob/patch-1/docs-ref-conceptual/spring-framework/configure-spring-data-gremlin-java-app-with-cosmos-db.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-data-gremlin-java-app-with-cosmos-db?view=azure-java-stable&branch=pr-en-us-611) (azure-java-stable) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C10%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201809101425024753-611%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0tc74FKwy%2F1ZUyieHDvGx8dWvSInEdIUAK77kpUGIYI%3D&st=2018-09-10T15%3A01%3A19Z&se=2018-10-11T15%3A06%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-data-gremlin-java-app-with-cosmos-db.md](https://github.com/v-maudel/azure-docs-sdk-java/blob/patch-1/docs-ref-conceptual/spring-framework/configure-spring-data-gremlin-java-app-with-cosmos-db.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-data-gremlin-java-app-with-cosmos-db?view=azure-java-stable&branch=pr-en-us-611) (azure-java-stable) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C10%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201809101427478703-611%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0dQnVOFhImhIw0jPYlnLeT0TSiyhebCp%2B5kGlnm356w%3D&st=2018-09-10T15%3A42%3A16Z&se=2018-10-11T15%3A47%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-maudel** [comment]
Thanks @brunoborges 
#sign-off

**Comment by v-maudel** [comment]
Hi @brunoborges , it seems I cannot sign-off automatically this PR and can't merge it either. 
Could you please Merge it or let me know if you will apply the changes in anothe PR?

Thanks in advance.

**Comment by v-maudel** [comment]
Thanks @brunoborges

**Pull request merged**
