### PR TITLE
C3607: Hardcoded EN locale in link  #254

### PR DESCRIPTION
**Pull request by carolinacmoravia**
@rloutlaw, could help to merge this PR in master branch? Many thanks!

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/servicebus.md](https://github.com/carolinacmoravia/azure-docs-sdk-java/blob/patch-10/docs-ref-services/servicebus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C6%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201711061538034243-293%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QI%2B7nbg1QmLc9VvU4HwSvCsai6atpEogmT2kepTBBoM%3D&st=2017-11-06T16%3A24%3A27Z&se=2017-12-07T16%3A29%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by carolinacmoravia** [comment]
#sign-off

**Comment by carolinacmoravia** [comment]
@PRMerger4, can you look at this PR that has not merged yet? Thank you

**Comment by carolinacmoravia** [comment]
#sign-off

**Pull request merged**
