### PR TITLE
Fixing some small errors

### PR DESCRIPTION
**Pull request by rmcmurray**
Changing the syntax for an index.yml file, and updating some docs so that ACS is the new AKS

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/index.yml](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20171117/docs-ref-conceptual/spring-framework/index.yml) | :x:Error | | [Details](#user-content-docs-ref-conceptual%2Fspring-framework%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="docs-ref-conceptual%2Fspring-framework%2Findex.yml"></a>
### [docs-ref-conceptual/spring-framework/index.yml](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20171117/docs-ref-conceptual/spring-framework/index.yml)
 - **[Error]** Unable to load file: docs-ref-conceptual/spring-framework/index.yml via processor: YamlDocumentProcessor.

<a name=""></a>
### []()
 - **[Error]** YamlDotNet.Core.SemanticErrorException: (Line: 31, Col: 64, Idx: 1337) - (Line: 31, Col: 109, Idx: 1382): While parsing a block mapping, did not find expected key.
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.GetInnerContexts(DocumentBuildParameters parameters, IEnumerable`1 processors, TemplateProcessor templateProcessor, IHostServiceCreator creator)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.BuildCore(DocumentBuildParameters parameters)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.BuildCore(DocumentBuildParameters parameter, IMarkdownServiceProvider markdownServiceProvider, BuildInfo currentBuildInfo, BuildInfo lastBuildInfo)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.Build(IList`1 parameters, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C19%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201711190431317787-305%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=F4yjbH%2BzAjQNfxvgx8bLCQYmgk%2B0YyWqW9NcYtN7Bfo%3D&st=2017-11-19T04%3A31%3A01Z&se=2017-12-20T04%3A36%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/index.yml](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20171117/docs-ref-conceptual/spring-framework/index.yml) | :x:Error | | [Details](#user-content-docs-ref-conceptual%2Fspring-framework%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="docs-ref-conceptual%2Fspring-framework%2Findex.yml"></a>
### [docs-ref-conceptual/spring-framework/index.yml](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20171117/docs-ref-conceptual/spring-framework/index.yml)
 - **[Error]** Unable to load file: docs-ref-conceptual/spring-framework/index.yml via processor: YamlDocumentProcessor.

<a name=""></a>
### []()
 - **[Error]** YamlDotNet.Core.SemanticErrorException: (Line: 30, Col: 64, Idx: 1328) - (Line: 30, Col: 108, Idx: 1372): While parsing a block mapping, did not find expected key.
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.GetInnerContexts(DocumentBuildParameters parameters, IEnumerable`1 processors, TemplateProcessor templateProcessor, IHostServiceCreator creator)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.BuildCore(DocumentBuildParameters parameters)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.BuildCore(DocumentBuildParameters parameter, IMarkdownServiceProvider markdownServiceProvider, BuildInfo currentBuildInfo, BuildInfo lastBuildInfo)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.Build(IList`1 parameters, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C19%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201711190517552382-305%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XboNlD9GTilHBqEOenIIgYTkBTIEOOH%2FMxI3gcJWFTc%3D&st=2017-11-19T05%3A17%3A13Z&se=2017-12-20T05%3A22%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/index.yml](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20171117/docs-ref-conceptual/spring-framework/index.yml) | :x:Error | | [Details](#user-content-docs-ref-conceptual%2Fspring-framework%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="docs-ref-conceptual%2Fspring-framework%2Findex.yml"></a>
### [docs-ref-conceptual/spring-framework/index.yml](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20171117/docs-ref-conceptual/spring-framework/index.yml)
 - **[Error]** Unable to load file: docs-ref-conceptual/spring-framework/index.yml via processor: YamlDocumentProcessor.

<a name=""></a>
### []()
 - **[Error]** YamlDotNet.Core.SemanticErrorException: (Line: 30, Col: 64, Idx: 1328) - (Line: 30, Col: 108, Idx: 1372): While parsing a block mapping, did not find expected key.
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.GetInnerContexts(DocumentBuildParameters parameters, IEnumerable`1 processors, TemplateProcessor templateProcessor, IHostServiceCreator creator)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.BuildCore(DocumentBuildParameters parameters)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.BuildCore(DocumentBuildParameters parameter, IMarkdownServiceProvider markdownServiceProvider, BuildInfo currentBuildInfo, BuildInfo lastBuildInfo)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.Build(IList`1 parameters, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C19%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201711190653381017-305%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=w37mkc0jJhDXOxzTZ1TS4K8phPspFJLiLWWgcW%2F8ZRk%3D&st=2017-11-19T06%3A52%3A56Z&se=2017-12-20T06%3A57%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/eclipse/azure-toolkit-for-eclipse-installation.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20171117/docs-ref-conceptual/eclipse/azure-toolkit-for-eclipse-installation.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/eclipse/azure-toolkit-for-eclipse-publish-spring-boot-docker-app.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20171117/docs-ref-conceptual/eclipse/azure-toolkit-for-eclipse-publish-spring-boot-docker-app.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/eclipse/azure-toolkit-for-eclipse.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20171117/docs-ref-conceptual/eclipse/azure-toolkit-for-eclipse.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/intellij/azure-toolkit-for-intellij-publish-spring-boot-docker-app.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20171117/docs-ref-conceptual/intellij/azure-toolkit-for-intellij-publish-spring-boot-docker-app.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/intellij/azure-toolkit-for-intellij.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20171117/docs-ref-conceptual/intellij/azure-toolkit-for-intellij.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/index.yml](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20171117/docs-ref-conceptual/spring-framework/index.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C19%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201711190731546003-305%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=aVrZuC%2FiDYxVyreLV0H%2FmehfB7%2FWpQODNqtVa0Ttu3c%3D&st=2017-11-19T07%3A54%3A32Z&se=2017-12-20T07%3A59%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rmcmurray** [comment]
#sign-off

**Pull request merged**
