### PR TITLE
Updating Spring Cosmos DB article

### PR DESCRIPTION
**Pull request by rmcmurray**
I have been testing this example for the past couple of weeks, and I have yet to get this working with 2.x.x of Spring Boot. There appear to be several breaking changes in several APIs that this example is using, so I am updating the article to require 1.5.x of Spring Boot.

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180705/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180705/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ03.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180705/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ03.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C21%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201807210130045986-541%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Ih9qPvh9GObR%2FDqKvlHnIUXpiHIFUaUy0kjoCyFnAuM%3D&st=2018-07-21T02%3A03%3A39Z&se=2018-08-21T02%3A08%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rmcmurray** [comment]
#sign-off

**Comment by rmcmurray** [comment]
Thanks, @brunoborges - I rearranged the order of the notes surrounding the section where I indicate the version of Spring that this applies to. That being said, I do not control the README file, which is in an entirely different repo.

However, I do not understand your request to remove the paths, which the article mentions are only examples, nor do I understand why you want the name of the package changed.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db.md](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180705/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180705/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ03.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180705/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/AZ03.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/JV01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180705/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/JV01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/JV02.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180705/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/JV02.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/JV03.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180705/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/JV03.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/PM01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180705/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/PM01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/RE01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180705/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/RE01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/RE02.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180705/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/RE02.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/SI01.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180705/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/SI01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/SI02.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180705/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/SI02.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/SI03.png](https://github.com/rmcmurray/azure-docs-sdk-java/blob/20180705/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-cosmos-db/SI03.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C22%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201807221528396501-541%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qwVulj3EWVVrIh1A57Jv91zu74OYJrtPCkU6VDPwDGU%3D&st=2018-07-22T16%3A00%3A30Z&se=2018-08-22T16%3A05%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
