### PR TITLE
CI Update

### PR DESCRIPTION
**Pull request by glibnub**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[6598733](https://github.com/Azure/azure-docs-sdk-java/pull/786/commits/65987330ef2dd568da2c1671ee2b3d7894c75820)_: 

:clock10: **Full build**: the average full build time is _69 min(s) 52 sec(s)_, this is based on the last _153_ build(s) for this repository.

 :warning: **This is a FULL build** due to the incremental build being disabled in configuration file (.openpublishing.publish.config.json in 'live' branch). For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[6598733](https://github.com/Azure/azure-docs-sdk-java/pull/786/commits/65987330ef2dd568da2c1671ee2b3d7894c75820)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-autogen/com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.ReconnectionTask.yml](https://github.com/Azure/azure-docs-sdk-java/blob/smoke-test/docs-ref-autogen/com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.ReconnectionTask.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.device.transport.amqps.amqpsiothubconnection.reconnectiontask.call?view=azure-java-stable&branch=pr-en-us-786) (azure-java-stable) |
[docs-ref-autogen/com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.yml](https://github.com/Azure/azure-docs-sdk-java/blob/smoke-test/docs-ref-autogen/com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.device.transport.amqps.amqpsiothubconnection.adddeviceoperationsession?view=azure-java-stable&branch=pr-en-us-786) (azure-java-stable) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C15%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201903152143317397-786%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jUnrXIQiqi8F1HGzKxOZFQWvOru49RX5IdgVTfjtz3g%3D&st=2019-03-15T22%3A52%3A13Z&se=2019-04-15T22%3A57%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[b6db955](https://github.com/Azure/azure-docs-sdk-java/pull/786/commits/b6db9552c7932d2b7a20f39fe3cae3f2bbfd149e)_: 

:clock10: **Full build**: the average full build time is _69 min(s) 47 sec(s)_, this is based on the last _154_ build(s) for this repository.

 :warning: **This is a FULL build** due to the incremental build being disabled in configuration file (.openpublishing.publish.config.json in 'live' branch). For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[b6db955](https://github.com/Azure/azure-docs-sdk-java/pull/786/commits/b6db9552c7932d2b7a20f39fe3cae3f2bbfd149e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-autogen/com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.ReconnectionTask.yml](https://github.com/Azure/azure-docs-sdk-java/blob/smoke-test/docs-ref-autogen/com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.ReconnectionTask.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.device.transport.amqps.amqpsiothubconnection.reconnectiontask.call?view=azure-java-stable&branch=pr-en-us-786) (azure-java-stable) |
[docs-ref-autogen/com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.yml](https://github.com/Azure/azure-docs-sdk-java/blob/smoke-test/docs-ref-autogen/com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.device.transport.amqps.amqpsiothubconnection.adddeviceoperationsession?view=azure-java-stable&branch=pr-en-us-786) (azure-java-stable) |
[docs-ref-autogen/com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.yml](https://github.com/Azure/azure-docs-sdk-java/blob/smoke-test/docs-ref-autogen/com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/com.microsoft.azure.servicebus.primitives.coremessagereceiver.abandonmessageasync?view=azure-java-stable&branch=pr-en-us-786) (azure-java-stable) |
[docs-ref-autogen/com.microsoft.azure.servicebus.primitives.CoreMessageSender.yml](https://github.com/Azure/azure-docs-sdk-java/blob/smoke-test/docs-ref-autogen/com.microsoft.azure.servicebus.primitives.CoreMessageSender.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/com.microsoft.azure.servicebus.primitives.coremessagesender.cancelscheduledmessageasync?view=azure-java-stable&branch=pr-en-us-786) (azure-java-stable) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C16%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201903152207440259-786%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Qa1AcN%2FMoLHAzdo5wODXpyCp4WbEEq6%2BWj0mFiFC0Xo%3D&st=2019-03-16T00%3A07%3A07Z&se=2019-04-16T00%3A12%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
@Taojunshen can you take a look?  Is this how PRs normally work here?

**Pull request merged**
