### PR TITLE
C9857: LOCBLOCKER: Missing ``` causing content blocked for localization

### PR DESCRIPTION
**Pull request by carolinacmoravia**
Hello, @rmcmurray,

Localization team has reported source content issue that causes localizable text to be blocked from localization.  

Unlocalized strings due to code block issue  
To resolve this issue, please, help to add the missing ```  as proposed change in this PR. 
 
Please, help to check my proposed file change into the article and help to merge if you agree with fix. If not, please, let me know either if you would like me to fix it in another way within this PR, if you prefer to fix it in another PR or if I should close this PR as by-design. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR. 
Many thanks in advance.

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md](https://github.com/carolinacmoravia/azure-docs-sdk-java/blob/patch-13/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C20%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201712201838467120-334%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=AZewFni77tb7SLB2UnFBWH%2Bd3kmgDBhs8lqHSTivbOQ%3D&st=2017-12-20T18%3A57%3A40Z&se=2018-01-20T19%3A02%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by carolinacmoravia** [comment]
#sign-off

**Comment by carolinacmoravia** [comment]
Hello, @rmcmurray,

Localization team has reported source content issue that causes localizable text to be blocked from localization.

Unlocalized strings due to code block issue
To resolve this issue, please, help to add the missing ``` as proposed change in this PR.

Please, help to check my proposed file change into the article and help to merge if you agree with fix. If not, please, let me know either if you would like me to fix it in another way within this PR, if you prefer to fix it in another PR or if I should close this PR as by-design. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR.
Many thanks in advance.

**Comment by carolinacmoravia** [comment]
Hello, @rmcmurray,

Localization team has reported source content issue that causes localizable text to be blocked from localization.

Unlocalized strings due to code block issue
To resolve this issue, please, help to add the missing ``` as proposed change in this PR.

Please, help to check my proposed file change into the article and help to merge if you agree with fix. If not, please, let me know either if you would like me to fix it in another way within this PR, if you prefer to fix it in another PR or if I should close this PR as by-design. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR.
Many thanks in advance.

Cc: @IshaSahni

**Comment by carolinacmoravia** [comment]
Hello, @rmcmurray,

Localization team has reported source content issue that causes localizable text to be blocked from localization.

Unlocalized strings due to code block issue
To resolve this issue, please, help to add the missing ``` as proposed change in this PR.

Please, help to check my proposed file change into the article and help to merge if you agree with fix. If not, please, let me know either if you would like me to fix it in another way within this PR, if you prefer to fix it in another PR or if I should close this PR as by-design. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR.
Many thanks in advance.

Cc: @ishasahni

**Comment by carolinacmoravia** [comment]
Hello, @rmcmurray,

Localization team has reported source content issue that causes localizable text to be blocked from localization.

Unlocalized strings due to code block issue
To resolve this issue, please, help to add the missing ``` as proposed change in this PR.

Please, help to check my proposed file change into the article and help to merge if you agree with fix. If not, please, let me know either if you would like me to fix it in another way within this PR, if you prefer to fix it in another PR or if I should close this PR as by-design. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR.
Many thanks in advance.

Cc: @ishasahni

**Comment by rmcmurray** [comment]
Thanks, that was obviously a typographic error.

#sign-off

**Comment by carolinacmoravia** [comment]
#sign-off

**Pull request merged**
