### PR TITLE
Update TOC to group them as Spring Boot, Data, Security and Cloud

### PR DESCRIPTION
**Pull request by Matthew-Dong**
New TOC for  “Getting Started Guides”

Getting Started Guide
- Spring Boot // Overview
              - Azure Key Vault
              - Azure Storage
              - Azure App Insights  
- Spring Data // Overview 
              - Azure Cosmos DB 
              - Azure Cosmos DB Gremlin API
- Spring Security // Overview
- Azure Active Directory
- Spring Cloud // Overview 
              - Azure Event Hub
              - Azure Event Hub Kafka API

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/toc.yml](https://github.com/Matthew-Dong/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub?view=azure-java-legacy&branch=pr-en-us-724) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub?view=azure-java-preview&branch=pr-en-us-724) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub?view=azure-java-stable&branch=pr-en-us-724) (azure-java-stable) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C7%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201812070407077719-724%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=aTEWlf0OQaElFAvTeDuOyYj3IFB8V1RdMCDdejASsu4%3D&st=2018-12-07T05%3A15%3A40Z&se=2019-01-07T05%3A20%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/toc.yml](https://github.com/Matthew-Dong/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub?view=azure-java-legacy&branch=pr-en-us-724) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub?view=azure-java-preview&branch=pr-en-us-724) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub?view=azure-java-stable&branch=pr-en-us-724) (azure-java-stable) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C7%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201812070416571563-724%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=R0V30UhK5FxAnmwFNjQs1bSkZoQq%2BypWraNjFY%2B2Z1Y%3D&st=2018-12-07T08%3A09%3A12Z&se=2019-01-07T08%3A14%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rmcmurray** [comment]
(Adding @rloutlaw to the discussion.)

First of all, I like the suggested rearrangement of the TOC by Spring subject area. However, one of my main points of concern is that the suggested changes will create a much-deeper TOC hierarchy than we are currently using, which I think would impact article discovery.

If you look at the current Spring TOC, we have four top-level contents items: *Getting Started Guides*, *Tutorials*, *Samples*, and *Reference*. The remaining content is all bucketed under those primary TOC items. In short, this is a two-dimensional structure, so any particular article requires a maximum of one to two clicks to find it.

That being said, the suggested TOC would move several articles into a third-tier of the hierarchy, (e.g. a three-dimensional structure), which would require additional effort for article discovery. Having seen that sort of deeper-level TOC hierarchy before, there were several customers who abandoned using the TOC because it became too-unwieldy for them to use.

With that in mind, I would personally advise against taking this suggested change, although I am curious to see what @rloutlaw thinks. I'm open to discussion of a way where we can keep a two-dimensional structure and still rearrange the articles into Spring-based subjects.

**Comment by brunoborges** [comment]
The less levels we have on the TOC, the better. 
But the structure makes sense.
The solution is to ensure the TOC items show up all expanded by default.

**Comment by Matthew-Dong** [comment]
Good point. 

We want a clear structure, meanwhile avoid hiding them. The new structure aligns with the way Spring organizes its projects, that may be more familiar to our customers.  

Expanding them by default sounds a good solution to me!

**Comment by rmcmurray** [comment]
Following up on our conversation earlier today, my initial worry was that having articles two levels deep in the TOC hierarchy might create a problem for content discoverability. @brunoborges suggested expanding the child nodes by default, which I could see becoming unnecessarily bloated quite rapidly, which would create an entirely separate problem for content discoverability.

That being said, I would propose one of the following two TOC layouts, which might serve our purposes without becoming unwieldly.

**Suggestion #1**: We could combine Yitao's and Bruno's suggestions and expand only the first-level children in the _Getting Started Guide_, and collapse the second-level children. For example:

* **Getting Started Guide** // _Expand children by default_
  * **Spring Boot** // _Collapse children by default_
    * Azure Key Vault
    * Azure Storage
    * Azure App Insights
  * **Spring Data** // _Collapse children by default_
    * Azure Cosmos DB
    * Azure Cosmos DB Gremlin API
  * **Spring Security** // _Collapse children by default_
    * Azure Active Directory
  * **Spring Cloud** // _Collapse children by default_
    * Azure Event Hub
    * Azure Event Hub Kafka API
* **Tutorials** // _Collapse children by default_
* **Samples** // _Collapse children by default_
* **Reference** // _Collapse children by default_

Or - we could promote the major Spring technology children to the parent level, and then collapse all children by default. For example:

* **Getting Started Guide** // _Collapse children by default_
* **Spring Boot** // _Collapse children by default_
  * Azure Key Vault
  * Azure Storage
  * Azure App Insights
* **Spring Data** // _Collapse children by default_
  * Azure Cosmos DB
  * Azure Cosmos DB Gremlin API
* **Spring Security** // _Collapse children by default_
  * Azure Active Directory
* **Spring Cloud** // _Collapse children by default_
  * Azure Event Hub
  * Azure Event Hub Kafka API
* **Tutorials** // _Collapse children by default_
* **Samples** // _Collapse children by default_
* **Reference** // _Collapse children by default_

What does anyone else think?

**Comment by brunoborges** [comment]
I suggest we go with the TOC that is best for the content we have today.
Once (if) we have more content, then we optimize the TOC again.

**Comment by Matthew-Dong** [comment]
@rmcmurray both suggestions work for me. Slightly prefer the 1st one, since we do not have that many toturials today. Could you approve/re-send the PR for this change? 

The key is to strucure the content in a Spring-native way. :)

**Comment by rmcmurray** [comment]
@Matthew-Dong, FYI – There is a blocking issue with the build process that is currently under investigation.

The past few PRs that we have submitted have failed to get built properly, (such as the [Build 38940 failed ](https://apidrop.visualstudio.com/6fb8cb7d-5623-420c-946b-ca74e63ac8ba/_build/results?buildId=38940) listed above), so this PR might be held up for a couple of days while the build issue is resolved.

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[6841f13](https://github.com/Matthew-Dong/azure-docs-sdk-java/pull/724/commits/6841f134cb305bc0e3f0d645adc3c01b5dbe80c1)_: 

:clock10: **Full build**: average full build time is _68 min(s) 17 sec(s)_ [calculated from last _81_ build(s)]

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[6841f13](https://github.com/Matthew-Dong/azure-docs-sdk-java/pull/724/commits/6841f134cb305bc0e3f0d645adc3c01b5dbe80c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/toc.yml](https://github.com/Matthew-Dong/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub?view=azure-java-legacy&branch=pr-en-us-724) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub?view=azure-java-preview&branch=pr-en-us-724) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub?view=azure-java-stable&branch=pr-en-us-724) (azure-java-stable) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C20%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201812201728121484-724%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QnKsgZJ2LqLWt8Web0XLUbWcll0avjOvCamf2LP%2B9XA%3D&st=2018-12-20T18%3A39%3A35Z&se=2019-01-20T18%3A44%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
