### PR TITLE
updated link for cloud shell on get started page.

### PR DESCRIPTION
**Pull request by georgewallace**

### CODE REVIEW

**Comment by georgewallace** [comment]
link for cloud shell has an s. removed it so link will work.

**Comment by rloutlaw** [comment]
Looks good to me! Thanks for the PR.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/java-sdk-azure-get-started.md](https://github.com/Azure/azure-docs-sdk-java/blob/georgewallace-patch-1/docs-ref-conceptual/java-sdk-azure-get-started.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C10%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201710101642262410-266%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=BYr5phkio4tEWJzgdOuf0wr3zlM%2B6ngO949gsPEV8sA%3D&st=2017-10-10T17%3A03%3A06Z&se=2017-11-10T17%3A08%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by georgewallace** [comment]
#sign-off

**Pull request merged**
