### PR TITLE
C54248: Closing code box

### PR DESCRIPTION
**Pull request by v-maudel**
Hello, @rmcmurray,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.
Many thanks in advance.

### CODE REVIEW

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[fbf9611](https://github.com/v-maudel/azure-docs-sdk-java/pull/736/commits/fbf96112dabb50d76fc8e57dbfddb3380c194742)_: 

:clock10: **Preparing**: average preparing time is _5 min(s) 53 sec(s)_

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[fbf9611](https://github.com/v-maudel/azure-docs-sdk-java/pull/736/commits/fbf96112dabb50d76fc8e57dbfddb3380c194742)_: 

:clock10: **Full build**: average full build time is _68 min(s) 18 sec(s)_ [calculated from last _63_ build(s)]

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by v-makoud** [comment]
Hello, @rmcmurray,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.
Many thanks in advance.

**Comment by v-maudel** [comment]
Hello, @rmcmurray,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.
Many thanks in advance.

CC: mbaldwin

**Comment by v-makoud** [comment]
Hello, @rmcmurray,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.
Many thanks in advance.

CC: @mbaldwin

**Comment by v-makoud** [comment]
Hello, @rmcmurray,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.
Many thanks in advance.

CC: @mbaldwin, @nokura, @arob98, @JennieHubbard

**Comment by v-makoud** [comment]
Hello, @rmcmurray,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.
Many thanks in advance.

CC: @mbaldwin, @nokura, @arob98, @JennieHubbard

**Comment by JennieHubbard** [comment]
Approved

**Comment by v-makoud** [comment]
#sign-off

**Comment by v-makoud** [comment]
we cant sign-off this PR, can any of you do it please?

@JennieHubbard, @mbaldwin, @nokura, @arob98, @JennieHubbardwe, @rmcmurray

**Comment by v-makoud** [comment]
#sign-off

**Comment by v-makoud** [comment]
we cant sign-off this PR, can any of you do it please?

@JennieHubbard, @mbaldwin, @nokura, @arob98, @rmcmurray

**Comment by v-makoud** [comment]
we cant sign-off this PR, can any of you do it please?

@JennieHubbard, @mbaldwin, @nokura, @arob98, @rmcmurray

**Comment by JennieHubbard** [comment]
@rloutlaw

**Pull request merged**
