### PR TITLE
M31735: Missing link in URL list

### PR DESCRIPTION
**Pull request by v-maudel**
Hi @rmcmurray, 
This fix comes from this [old PR](https://github.com/Azure/azure-docs-sdk-java/pull/648), it seems it wasn't fixed properly. 
Could you please take a look and merge if agree?

Regards.
Cc: @brunoborges , @rloutlaw, @mbaldwin, @v-makoud

### CODE REVIEW

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[2a3b32e](https://github.com/v-maudel/azure-docs-sdk-java/pull/768/commits/2a3b32e9295ab62d7a8adc685ecd273e74eff8ad)_: 

:clock10: **Preparing**: average preparing time is _5 min(s) 46 sec(s)_

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[2a3b32e](https://github.com/v-maudel/azure-docs-sdk-java/pull/768/commits/2a3b32e9295ab62d7a8adc685ecd273e74eff8ad)_: 

:clock10: **Full build**: average full build time is _68 min(s) 53 sec(s)_ [calculated from last _117_ build(s)]

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[2a3b32e](https://github.com/v-maudel/azure-docs-sdk-java/pull/768/commits/2a3b32e9295ab62d7a8adc685ecd273e74eff8ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md](https://github.com/v-maudel/azure-docs-sdk-java/blob/patch-6/docs-ref-conceptual/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-stable&branch=pr-en-us-768) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-preview&branch=pr-en-us-768) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-legacy&branch=pr-en-us-768) (azure-java-legacy) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C5%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201902051403497065-768%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UMJLRXOYk6Xhb5GghRD1YZXomrfi7HVvKjA8OC4ZJEY%3D&st=2019-02-05T15%3A15%3A15Z&se=2019-03-08T15%3A20%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[249d540](https://github.com/v-maudel/azure-docs-sdk-java/pull/768/commits/249d540afca94554928484728e0dc18544f6da96)_: 

:clock10: **Preparing**: average preparing time is _5 min(s) 46 sec(s)_

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[249d540](https://github.com/v-maudel/azure-docs-sdk-java/pull/768/commits/249d540afca94554928484728e0dc18544f6da96)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md](https://github.com/v-maudel/azure-docs-sdk-java/blob/patch-6/docs-ref-conceptual/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-stable&branch=pr-en-us-768) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-preview&branch=pr-en-us-768) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-legacy&branch=pr-en-us-768) (azure-java-legacy) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C5%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201902051404081237-768%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=DlvfOA3nb4x996qdI5moDoOBveeCk2XeCaccu%2BbloF8%3D&st=2019-02-05T16%3A32%3A39Z&se=2019-03-08T16%3A37%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-makoud** [comment]
Hi @rmcmurray,
This fix comes from this [old PR](https://github.com/Azure/azure-docs-sdk-java/pull/648), it seems it wasn't fixed properly.
Could you please take a look and merge if agree?

Regards.
Cc: @brunoborges , @rloutlaw, @mbaldwin, @v-maudel

**Comment by v-maudel** [comment]
Hi @rmcmurray,
This fix comes from this [old PR](https://github.com/Azure/azure-docs-sdk-java/pull/648), it seems it wasn't fixed properly.
Could you please take a look and merge if agree?

Regards.
Cc: @brunoborges , @rloutlaw, @mbaldwin, @v-maudel @Alisha-Acharya

**Comment by v-makoud** [comment]
Hi @rmcmurray,
This fix comes from this [old PR](https://github.com/Azure/azure-docs-sdk-java/pull/648), it seems it wasn't fixed properly.
Could you please take a look and merge if agree?

Regards.
Cc: @brunoborges , @rloutlaw, @mbaldwin, @v-maudel @Alisha-Acharya

**Comment by v-makoud** [comment]
Hi @rmcmurray,
This fix comes from this [old PR](https://github.com/Azure/azure-docs-sdk-java/pull/648), it seems it wasn't fixed properly.
Could you please take a look and merge if agree?

Regards.
Cc: @brunoborges , @rloutlaw, @mbaldwin, @v-maudel @Alisha-Acharya

**Pull request merged**
