### PR TITLE
Add tutorial for aad b2c oidc for spring security.

### PR DESCRIPTION
**Pull request by Incarnation-p-lee**
Signed-off-by: Pan Li <panli@microsoft.com>

### CODE REVIEW

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[8d28266](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/pull/778/commits/8d2826600d0349f67c54aea26c67f1a2accf17a5)_: 

:clock10: **Preparing**: average preparing time is _5 min(s) 45 sec(s)_

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[8d28266](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/pull/778/commits/8d2826600d0349f67c54aea26c67f1a2accf17a5)_: 

:clock10: **Full build**: average full build time is _69 min(s) 25 sec(s)_ [calculated from last _138_ build(s)]

> Note: A full build takes more time than an incremental build. This is the expected behavior of the build system.

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[8d28266](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/pull/778/commits/8d2826600d0349f67c54aea26c67f1a2accf17a5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-stable&branch=pr-en-us-778) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-preview&branch=pr-en-us-778) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-legacy&branch=pr-en-us-778) (azure-java-legacy) | [Details](#user-content-docs-ref-conceptual%2Fspring-framework%2Fconfigure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md)
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/AZ1.PNG](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/AZ1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-legacy&branch=pr-en-us-778) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-preview&branch=pr-en-us-778) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-stable&branch=pr-en-us-778) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/AZ2.PNG](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/AZ2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-legacy&branch=pr-en-us-778) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-preview&branch=pr-en-us-778) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-stable&branch=pr-en-us-778) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/AZ3.PNG](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/AZ3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-legacy&branch=pr-en-us-778) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-preview&branch=pr-en-us-778) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-stable&branch=pr-en-us-778) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/AZ4.PNG](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/AZ4.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-legacy&branch=pr-en-us-778) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-preview&branch=pr-en-us-778) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-stable&branch=pr-en-us-778) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/AZ5.PNG](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/AZ5.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-legacy&branch=pr-en-us-778) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-preview&branch=pr-en-us-778) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-stable&branch=pr-en-us-778) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/B2C1.PNG](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/B2C1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-legacy&branch=pr-en-us-778) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-preview&branch=pr-en-us-778) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-stable&branch=pr-en-us-778) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/B2C2.PNG](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/B2C2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-legacy&branch=pr-en-us-778) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-preview&branch=pr-en-us-778) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-stable&branch=pr-en-us-778) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/B2C3.PNG](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/B2C3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-legacy&branch=pr-en-us-778) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-preview&branch=pr-en-us-778) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-stable&branch=pr-en-us-778) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/B2C4.PNG](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/B2C4.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-legacy&branch=pr-en-us-778) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-preview&branch=pr-en-us-778) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-stable&branch=pr-en-us-778) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/B2C5.PNG](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/B2C5.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/b2c5.png?view=azure-java-stable&branch=pr-en-us-778) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/LO1.PNG](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/LO1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-legacy&branch=pr-en-us-778) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-preview&branch=pr-en-us-778) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-stable&branch=pr-en-us-778) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/LO2.PNG](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/LO2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-legacy&branch=pr-en-us-778) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-preview&branch=pr-en-us-778) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-stable&branch=pr-en-us-778) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/LO3.PNG](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/LO3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-legacy&branch=pr-en-us-778) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-preview&branch=pr-en-us-778) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-stable&branch=pr-en-us-778) (azure-java-stable) |
[docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/SI.PNG](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc/SI.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-legacy&branch=pr-en-us-778) (azure-java-legacy)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-preview&branch=pr-en-us-778) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-stable&branch=pr-en-us-778) (azure-java-stable) |

<a name="docs-ref-conceptual%2Fspring-framework%2Fconfigure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md"></a>
### [docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md](https://github.com/Incarnation-p-lee/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md)
 - **Line 248**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/spring-framework/Templates).
 - **Line 248**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/spring-framework/Templates).
 - **Line 248**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/spring-framework/Templates).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C1%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201903010121220713-778%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BakNaDCqEn%2BmdBjir2RUQQGhcKNWfrdrtM4hhzsJIe8%3D&st=2019-03-01T02%3A37%3A22Z&se=2019-04-01T02%3A42%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Matthew-Dong** [comment]
The toc.yml file should be updated to include this tutorial in the TOC of Spring page.

**Comment by Incarnation-p-lee** [comment]
close this as new one add for resolve comments.

**Pull request closed without merging**
