### PR TITLE
C62241: Fixing hyperlink syntax

### PR DESCRIPTION
**Pull request by v-maudel**
Hello, @rmcmurray,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.  
Description: missing brackets () in source file prevent hyperlink from being created.  

Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.
Many thanks in advance.

### CODE REVIEW

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[7884ade](https://github.com/v-maudel/azure-docs-sdk-java/pull/761/commits/7884ade660566286a837b387642982507e3590c6)_: 

:clock10: **Preparing**: average preparing time is _5 min(s) 46 sec(s)_

**Comment by rmcmurray** [comment]
This change looks good to me - #sign-off

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[7884ade](https://github.com/v-maudel/azure-docs-sdk-java/pull/761/commits/7884ade660566286a837b387642982507e3590c6)_: 

:clock10: **Full build**: average full build time is _68 min(s) 37 sec(s)_ [calculated from last _108_ build(s)]

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by v-makoud** [comment]
#sign-off

**Comment by v-makoud** [comment]
Thanks so much @rmcmurray , although it seems it wasn't automatically merged with the sign-off. Could you please Merge it manually on your side or ask some manager to merge it?
Regards.
CC @mbaldwin

**Comment by v-maudel** [comment]
Thanks so much @rmcmurray , although it seems it wasn't automatically merged with the sign-off. Could you please Merge it manually on your side or ask some manager to merge it?
Regards.
CC @mbaldwin @arob98 @JennieHubbard @Alisha-Acharya

**Comment by v-maudel** [comment]
Hi @rmcmurray , It seems this wasn't automatically merged with the sign-off. Could you please Merge it manually on your side or ask some manager to merge it?
Regards.
CC @mbaldwin @arob98 @JennieHubbard @Alisha-Acharya

**Comment by JennieHubbard** [comment]
@Taojunshen can you merge this?

**Comment by v-makoud** [comment]
@Taojunshen can you merge this?

**Comment by v-makoud** [comment]
@Taojunshen can you merge this?

**Pull request merged**
