### PR TITLE
C8879: Inconsistent format in target version due to incorrect indenta…

### PR DESCRIPTION
**Pull request by carolinacmoravia**
…tion

Hello, @rmcmurray,

Localization team has reported source content issue that causes localized version to have different format compared to en-us version.  
The indentation is wrongly located in the article. 
  
Please, help to check my proposed file change into the article and help to merge if you agree with fix. If not, please, let me know either if you would like me to fix it in another way within this PR, if you prefer to fix it in another PR, or if I should close this PR as by-design. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR.

Many thanks in advance.

### CODE REVIEW

**Comment by rmcmurray** [comment]
@carolinacmoravia - this suggested change looks great to me; thanks!

**Comment by carolinacmoravia** [comment]
Thank you, @rmcmurray! :)

#sign-off

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/intellij/azure-toolkit-for-intellij-publish-as-docker-container.md](https://github.com/carolinacmoravia/azure-docs-sdk-java/blob/patch-12/docs-ref-conceptual/intellij/azure-toolkit-for-intellij-publish-as-docker-container.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C12%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201712121751321820-328%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=WBCpz1SqgiKwubxE%2Bren2PsosTDObG3Rf4Su%2Fk47XlI%3D&st=2017-12-12T18%3A10%3A47Z&se=2018-01-12T18%3A15%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by carolinacmoravia** [comment]
#sign-off

**Comment by carolinacmoravia** [comment]
Please, @rmcmurray, try to #sign-off

**Comment by rmcmurray** [comment]
Sorry, @carolinacmoravia - I saw that you had signed off and I thought that was good enough. ;-)

#sign-off

**Comment by carolinacmoravia** [comment]
#sign-off

**Comment by carolinacmoravia** [comment]
#sign-off

**Comment by carolinacmoravia** [comment]
Could you help me to merge this PR, @v-thepet? Thank you!

**Comment by carolinacmoravia** [comment]
Could you help me to merge this PR, @v-thepet? Thank you!

**Comment by carolinacmoravia** [comment]
Could you help me to merge this PR, @v-thepet? Thank you!

@ishasahni1

**Comment by carolinacmoravia** [comment]
Could you help me to merge this PR, @v-thepet? Thank you!

@ishasahni1

**Comment by carolinacmoravia** [comment]
Could you help me to merge this PR, @v-thepet? Thank you!

@ishasahni1

**Comment by carolinacmoravia** [comment]
#sign-off

**Comment by carolinacmoravia** [comment]
Could you help me to merge this PR, @v-thepet? Thank you!

@ishasahni1

**Comment by carolinacmoravia** [comment]
Could you help me to merge this PR, @v-thepet? Thank you!

@ishasahni1

**Comment by carolinacmoravia** [comment]
#sign-off

**Pull request merged**
