### PR TITLE
Update per request from engineering

### PR DESCRIPTION
**Pull request by mrbullwinkle**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[82c65ff](https://github.com/Azure/azure-docs-sdk-java/pull/737/commits/82c65ffbff22f012aa89613d66563c1892e5a5f1)_: 

:clock10: **Pending**: waiting for processors ([42](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, click [here](https://sitehelp.microsoft.com/) to report any potential performance downgrade issues, or you could view [OPS Portal](https://ops.microsoft.com/#/statistic) for trend of build queue length.

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[82c65ff](https://github.com/Azure/azure-docs-sdk-java/pull/737/commits/82c65ffbff22f012aa89613d66563c1892e5a5f1)_: 

:clock10: **Preparing**: average preparing time is _5 min(s) 54 sec(s)_

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[82c65ff](https://github.com/Azure/azure-docs-sdk-java/pull/737/commits/82c65ffbff22f012aa89613d66563c1892e5a5f1)_: 

:clock10: **Full build**: average full build time is _68 min(s) 18 sec(s)_ [calculated from last _65_ build(s)]

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[f1b1aaf](https://github.com/Azure/azure-docs-sdk-java/pull/737/commits/f1b1aaf7ba3a03ea0f752521d533b4cfd4ec6c62)_: 

:clock10: **Pending**: waiting for processors ([39](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, click [here](https://sitehelp.microsoft.com/) to report any potential performance downgrade issues, or you could view [OPS Portal](https://ops.microsoft.com/#/statistic) for trend of build queue length.

**Comment by mrbullwinkle** [comment]
Something weird happened with this PR additional files were just changed by something other than me. Closing and opening a new one.

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[82c65ff](https://github.com/Azure/azure-docs-sdk-java/pull/737/commits/82c65ffbff22f012aa89613d66563c1892e5a5f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-boot-java-applicationinsights.md](https://github.com/Azure/azure-docs-sdk-java/blob/mrbullwinkle-patch-1/docs-ref-conceptual/spring-framework/configure-spring-boot-java-applicationinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-java-applicationinsights?view=azure-java-stable&branch=pr-en-us-737) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-java-applicationinsights?view=azure-java-preview&branch=pr-en-us-737) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-java-applicationinsights?view=azure-java-legacy&branch=pr-en-us-737) (azure-java-legacy) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C18%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201812180200332563-737%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KjMgrNS5%2BNtX13MiAdViqxljAHHWa1tKI%2Bj2s4klcHk%3D&st=2018-12-18T03%3A09%3A33Z&se=2019-01-18T03%3A14%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[f1b1aaf](https://github.com/Azure/azure-docs-sdk-java/pull/737/commits/f1b1aaf7ba3a03ea0f752521d533b4cfd4ec6c62)_: 

:clock10: **Preparing**: average preparing time is _5 min(s) 54 sec(s)_

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[f1b1aaf](https://github.com/Azure/azure-docs-sdk-java/pull/737/commits/f1b1aaf7ba3a03ea0f752521d533b4cfd4ec6c62)_: 

### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified commit because branch mrbullwinkle-patch-1 has been deleted or has been force pushed: fatal: Could not parse object &#39;f1b1aaf7ba3a03ea0f752521d533b4cfd4ec6c62&#39;.


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C18%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201812180207128358-737%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zPbpktHSDYygzQ1uLYIQQQR7J6WL26gLxf5oRLZxZ2s%3D&st=2018-12-18T03%3A13%3A27Z&se=2019-01-18T03%3A18%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
