### PR TITLE
C2985:  LOCBLOCKER - Same name for two files

### PR DESCRIPTION
**Pull request by carolinacmoravia**
Hi, @rloutlaw,
In the localization process, multiple input files are attempting to write to the same output file. This  seems to be caused by the following  two source files that have the same filename with different extension, but both are attempting to write to the same output file:
https://github.com/Azure/azure-docs-sdk-java/blob/live/docs-ref-services/dns.md
https://github.com/Azure/azure-docs-sdk-java/blob/live/docs-ref-autogen/com.microsoft.azure.management.dns.yml

**dns.md**  Vs. **dns.yml**

Could you help to review and modify the names to avoid this problem, please?

Many thanks in advance for your time and support! :)

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/dns.md](https://github.com/carolinacmoravia/azure-docs-sdk-java/blob/patch-7/docs-ref-services/dns.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C4%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201710041851403971-258%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=S%2Bmr97g3xYWstv69vbrcJH81EBzjNU1JkOMRZn8ptNM%3D&st=2017-10-04T19%3A11%3A25Z&se=2017-10-05T19%3A21%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by carolinacmoravia** [comment]
Hi, @rloutlaw,
Could you help to review and modify the names to avoid this problem, please?
Many thanks in advance for your time and support! :)

**Comment by carolinacmoravia** [comment]
Hi, @rloutlaw,
Could you help to review and modify the names to avoid this problem, please?
Many thanks in advance for your time and support! :)

Cc: @SunnyDeng

**Comment by carolinacmoravia** [comment]
Hi, @rloutlaw,
Could you help to review and modify the names to avoid this problem, please?
Many thanks in advance for your time and support! :)

Cc: @SunnyDeng

**Comment by carolinacmoravia** [comment]
Hi, @rloutlaw,
Could you help to review and modify the names to avoid this problem, please?
Many thanks in advance for your time and support! :)

Cc: @ishasahni1

**Pull request merged**
