### PR TITLE
Merge into live to update some breaking content per Robert

### PR DESCRIPTION
**Pull request by yunyunyunyun**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-autogen/com.microsoft.azure.sdk.iot.device.transport._transport_utils.yml](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-autogen/com.microsoft.azure.sdk.iot.device.transport._transport_utils.yml) | :white_check_mark:Succeeded | |
[docs-ref-autogen/com.microsoft.azure.sdk.iot.service.transport._transport_utils.yml](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-autogen/com.microsoft.azure.sdk.iot.service.transport._transport_utils.yml) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/index.yml](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/index.yml) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/java-azure-tools.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/java-azure-tools.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/media/spring.svg](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/media/spring.svg) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/toc.yml](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C5%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201712051905515050-325%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cdjotLvvf5YZ75dTUpt7zgZFhQ3f1hisuVvRsg7X6NU%3D&st=2017-12-05T19%3A54%3A04Z&se=2018-01-05T19%3A59%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
@rloutlaw I'm going to sign off and merge this per your IM which states "Hey Mike-can you or Yun help me with an out of band publish for our Java content repo? I need a merge from master into live and I don’t have permissions to do it. " and "Picking up some changes for some late breaking content we hacked up last night. "  checks have passed so I'm going to move forward.  #sign-off

**Comment by mikekinsman** [comment]
#sign-off

**Comment by rloutlaw** [comment]
@mikekinsman  thanks. Can you or @yunyunyunyun merge this PR? I don't have merge-to-live permissions for this repo.

**Comment by mikekinsman** [comment]
@rloutlaw  merging.  @yunyunyunyun

**Pull request merged**
