### PR TITLE
C54248: Adding breakline after code-block ends

### PR DESCRIPTION
**Pull request by v-maudel**
Previous change made https://github.com/Azure/azure-docs-sdk-java/pull/721 needs an extra fix.
Description: Adding break-line after code-bloc ending.
CC: @rmcmurray,, @v-makoud

### CODE REVIEW

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[533e927](https://github.com/v-maudel/azure-docs-sdk-java/pull/735/commits/533e92719582ee1ea2e87b741bfec921de8f692c)_: 

:clock10: **Preparing**: average preparing time is _5 min(s) 53 sec(s)_

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[533e927](https://github.com/v-maudel/azure-docs-sdk-java/pull/735/commits/533e92719582ee1ea2e87b741bfec921de8f692c)_: 

:clock10: **Full build**: average full build time is _68 min(s) 18 sec(s)_ [calculated from last _63_ build(s)]

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by openpublishbuild** [comment]
OPS Build status updates of commit _[533e927](https://github.com/v-maudel/azure-docs-sdk-java/pull/735/commits/533e92719582ee1ea2e87b741bfec921de8f692c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md](https://github.com/v-maudel/azure-docs-sdk-java/blob/patch-2/docs-ref-conceptual/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-stable&branch=pr-en-us-735) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-preview&branch=pr-en-us-735) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?view=azure-java-legacy&branch=pr-en-us-735) (azure-java-legacy) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C17%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201812171252396916-735%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=WislWg5Bgdq4wHMVmSVajcZTINS1nV9v3ODyrcI71wY%3D&st=2018-12-17T14%3A02%3A14Z&se=2019-01-17T14%3A07%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-makoud** [comment]
Previous change made #721 needs an extra fix.
Description: Adding break-line after code-bloc ending.

**Comment by v-maudel** [comment]
Hi @rmcmurray,, 
Previous change made https://github.com/Azure/azure-docs-sdk-java/pull/721 needs an extra fix.
Description: Adding break-line after code-bloc ending.
CC: @v-makoud @mbaldwin

**Comment by v-makoud** [comment]
Hi @rmcmurray,,
Previous change made #721 needs an extra fix.
Description: Adding break-line after code-bloc ending.
CC: @v-maudel @mbaldwin

**Comment by v-makoud** [comment]
Hi @rmcmurray,
Previous change made #721 needs an extra fix.
Description: Adding break-line after code-bloc ending.
CC: @v-maudel @mbaldwin, @arob98, @JennieHubbard, @nokura

**Comment by v-makoud** [comment]
Hi @rmcmurray,
Previous change made #721 needs an extra fix.
Description: Adding break-line after code-bloc ending.
CC: @v-maudel @mbaldwin, @arob98, @JennieHubbard, @nokura

**Comment by JennieHubbard** [comment]
Approved

**Comment by v-makoud** [comment]
#sign-off

**Comment by v-makoud** [comment]
we cant sign-off this PR, can any of you do it please?

@JennieHubbard, @rmcmurray, @v-maudel @mbaldwin, @arob98, @nokura

**Comment by v-maudel** [comment]
Hi, we cant sign-off this PR, can any of you do it please?

@JennieHubbard, @rmcmurray, @v-maudel @mbaldwin, @arob98, @Alisha-Acharya

**Comment by JennieHubbard** [comment]
@Taojunshen can you merge?

**Comment by v-makoud** [comment]
Hi, we cant sign-off this PR, can any of you do it please?

@JennieHubbard, @rmcmurray, @v-maudel @mbaldwin, @arob98, @Alisha-Acharya @Taojunshen

**Comment by v-makoud** [comment]
Hi, we cant sign-off this PR, can any of you do it please?

@JennieHubbard, @rmcmurray, @v-maudel @mbaldwin, @arob98, @Alisha-Acharya @Taojunshen

**Comment by JennieHubbard** [comment]
@rloutlaw Can you take a look at this?

**Comment by rloutlaw** [comment]
I'll take care of this.

**Pull request merged**
