### PR TITLE
VALIDATION fixes

### PR DESCRIPTION
**Pull request by mSarts**

### CODE REVIEW

**Comment by mSarts** [comment]
NOTE: multiple-h1s is not the case. In the warning, multiple other files are pointing to the same file. The file itself only has one H1. For duplicate-h1s, the two files listed are in fact the same file.

**Comment by mSarts** [comment]
**Global effort to fix build validation errors**

@sima-zhu 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

NOTES:
*Multiple-h1s is not the case. In the warning, multiple other files are pointing to the same file. The file itself only has one H1. For duplicate-h1s, the two files listed are in fact the same file.

*Additional fixes for the following files are covered in the following PRs:
[docs-ref-services/legacy/sql.md](https://github.com/Azure/azure-docs-sdk-java/blob/main/docs-ref-services/legacy/sql.md) https://github.com/Azure/azure-docs-sdk-java/pull/2242

[docs-ref-services/preview/sql.md](https://github.com/Azure/azure-docs-sdk-java/blob/main/docs-ref-services/preview/sql.md) https://github.com/Azure/azure-docs-sdk-java/pull/2240

**Comment by mSarts** [comment]
Global effort to fix build validation errors

@sima-zhu

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

NOTES:
*Multiple-h1s is not the case. In the warning, multiple other files are pointing to the same file. The file itself only has one H1. For duplicate-h1s, the two files listed are in fact the same file.

*Additional fixes for the following files are covered in the following PRs:
[docs-ref-services/legacy/sql.md](https://github.com/Azure/azure-docs-sdk-java/blob/main/docs-ref-services/legacy/sql.md) https://github.com/Azure/azure-docs-sdk-java/pull/2242

[docs-ref-services/preview/sql.md](https://github.com/Azure/azure-docs-sdk-java/blob/main/docs-ref-services/preview/sql.md) https://github.com/Azure/azure-docs-sdk-java/pull/2240

**Review by sima-zhu — APPROVED** [review]

**Comment by RedZephyr13** [comment]
#sign-off

**Pull request merged**
