### PR TITLE
package version update for 1.31.0 release.

### PR DESCRIPTION
**Pull request by BrianMouncer**

### CODE REVIEW

**Comment by BrianMouncer** [comment]
@danieljurek
@JimSuplizio

**Comment by JimSuplizio** [comment]
@BrianMouncer, in the future you should assign this PR to yourself and add Daniel and I as reviewers.

**Review by JimSuplizio — APPROVED** [review]
1.31.0 was released on Friday, August 4th. I'm good with this update.

**Review by danieljurek — APPROVED** [review]

**Comment by BrianMouncer** [comment]
> @BrianMouncer, in the future you should assign this PR to yourself and add Daniel and I as reviewers.

I am unable to add specific reviewer to PRs in this repo, only tag people in comments, and the initial assignee is set when the PR is first created and I can not edit it after.

**Pull request merged**
