### PR TITLE
Major update to Java TOC

### PR DESCRIPTION
**Pull request by brunoborges**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/toc.yml](https://github.com/Azure/azure-docs-sdk-java/blob/new-java-toc/docs-ref-conceptual/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/azure/includes/azure-toolkit-additional-resources?view=azure-java-stable&branch=pr-en-us-568) (azure-java-stable) | [Details](#user-content-docs-ref-conceptual%2Ftoc.yml)
[azure-java-stable/azure/toc.json](https://github.com/Azure/azure-docs-sdk-java/blob/new-java-toc/azure-java-stable/azure/toc.json) | :warning:Warning | | [Details](#user-content-azure-java-stable%2Fazure%2Ftoc.json)

<a name="docs-ref-conceptual%2Ftoc.yml"></a>
### [docs-ref-conceptual/toc.yml](https://github.com/Azure/azure-docs-sdk-java/blob/new-java-toc/docs-ref-conceptual/toc.yml)
 - **[Warning]** Invalid file link:(~/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-from-container-registry-using-maven-plugin).
 - **[Warning]** Invalid file link:(~/docs-ref-conceptual/spring-framework/deploy-containerized-spring-boot-java-app-with-maven-plugin).
 - **[Warning]** Invalid file link:(~/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin).

<a name="azure-java-stable%2Fazure%2Ftoc.json"></a>
### [azure-java-stable/azure/toc.json](https://github.com/Azure/azure-docs-sdk-java/blob/new-java-toc/azure-java-stable/azure/toc.json)
 - **[Warning]** Toc node with title: &#39;Deploy to App Service with Maven&#39;, relative path &#39;&#39;, href &#39;spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable&#39; is invalid. Please make sure the node link does not exceed the docset. Reference error message: path: &#39;deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable&#39; contains invalid path char: ?
 - **[Warning]** Toc node with title: &#39;Deploy to App Service from Azure Container Registry&#39;, relative path &#39;&#39;, href &#39;spring-framework/deploy-spring-boot-java-app-from-container-registry-using-maven-plugin?view=azure-java-stable&#39; is invalid. Please make sure the node link does not exceed the docset. Reference error message: path: &#39;deploy-spring-boot-java-app-from-container-registry-using-maven-plugin?view=azure-java-stable&#39; contains invalid path char: ?

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C11%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201808110344385783-568%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0OHN8N9A46R4JVB6W1L9Kjdj84IbUqBKGbcTdisNWe8%3D&st=2018-08-11T04%3A23%3A08Z&se=2018-09-11T04%3A28%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/toc.yml](https://github.com/Azure/azure-docs-sdk-java/blob/new-java-toc/docs-ref-conceptual/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/azure/includes/azure-toolkit-additional-resources?view=azure-java-stable&branch=pr-en-us-568) (azure-java-stable) | [Details](#user-content-docs-ref-conceptual%2Ftoc.yml)
[azure-java-stable/azure/toc.json](https://github.com/Azure/azure-docs-sdk-java/blob/new-java-toc/azure-java-stable/azure/toc.json) | :warning:Warning | | [Details](#user-content-azure-java-stable%2Fazure%2Ftoc.json)
[docs-ref-autogen/com.microsoft.azure.sdk.iot.service.transport._transport_utils.yml](https://github.com/Azure/azure-docs-sdk-java/blob/new-java-toc/docs-ref-autogen/com.microsoft.azure.sdk.iot.service.transport._transport_utils.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.service.transport._transport_utils?view=azure-java-stable&branch=pr-en-us-568) (azure-java-stable) |

<a name="docs-ref-conceptual%2Ftoc.yml"></a>
### [docs-ref-conceptual/toc.yml](https://github.com/Azure/azure-docs-sdk-java/blob/new-java-toc/docs-ref-conceptual/toc.yml)
 - **[Warning]** Invalid file link:(~/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-from-container-registry-using-maven-plugin).
 - **[Warning]** Invalid file link:(~/docs-ref-conceptual/spring-framework/deploy-containerized-spring-boot-java-app-with-maven-plugin).
 - **[Warning]** Invalid file link:(~/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin).

<a name="azure-java-stable%2Fazure%2Ftoc.json"></a>
### [azure-java-stable/azure/toc.json](https://github.com/Azure/azure-docs-sdk-java/blob/new-java-toc/azure-java-stable/azure/toc.json)
 - **[Warning]** Toc node with title: &#39;Deploy to App Service with Maven&#39;, relative path &#39;&#39;, href &#39;spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable&#39; is invalid. Please make sure the node link does not exceed the docset. Reference error message: path: &#39;deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable&#39; contains invalid path char: ?
 - **[Warning]** Toc node with title: &#39;Deploy to App Service from Azure Container Registry&#39;, relative path &#39;&#39;, href &#39;spring-framework/deploy-spring-boot-java-app-from-container-registry-using-maven-plugin?view=azure-java-stable&#39; is invalid. Please make sure the node link does not exceed the docset. Reference error message: path: &#39;deploy-spring-boot-java-app-from-container-registry-using-maven-plugin?view=azure-java-stable&#39; contains invalid path char: ?

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C11%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201808110353585227-568%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wQlCIpUe3gvm3eCZqbZ%2Bad3%2B7J%2BS5mDiaF%2FIMJoeX3g%3D&st=2018-08-11T05%3A06%3A09Z&se=2018-09-11T05%3A11%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-autogen/com.microsoft.azure.sdk.iot.service.transport._transport_utils.yml](https://github.com/Azure/azure-docs-sdk-java/blob/new-java-toc/docs-ref-autogen/com.microsoft.azure.sdk.iot.service.transport._transport_utils.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.service.transport._transport_utils.javaserviceclientidentifier?view=azure-java-stable&branch=pr-en-us-568) (azure-java-stable) |
[docs-ref-conceptual/toc.yml](https://github.com/Azure/azure-docs-sdk-java/blob/new-java-toc/docs-ref-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/includes/azure-toolkit-additional-resources?view=azure-java-stable&branch=pr-en-us-568) (azure-java-stable) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C11%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201808110432241121-568%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=G%2FvHyHOWmY%2FbQrdeR1oMtxp3oQ0evYJ0Cl%2B7V35o2Pw%3D&st=2018-08-11T05%3A50%3A55Z&se=2018-09-11T05%3A55%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-autogen/com.microsoft.azure.sdk.iot.service.transport._transport_utils.yml](https://github.com/Azure/azure-docs-sdk-java/blob/new-java-toc/docs-ref-autogen/com.microsoft.azure.sdk.iot.service.transport._transport_utils.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.service.transport._transport_utils.javaserviceclientidentifier?view=azure-java-stable&branch=pr-en-us-568) (azure-java-stable) |
[docs-ref-conceptual/toc.yml](https://github.com/Azure/azure-docs-sdk-java/blob/new-java-toc/docs-ref-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/includes/azure-toolkit-additional-resources?view=azure-java-stable&branch=pr-en-us-568) (azure-java-stable) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C14%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201808141725109450-568%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0xsTuDGBu7vnwPafiuFcAlMnNCF45Lzs7%2BStb%2Fds1V0%3D&st=2018-08-14T19%3A23%3A08Z&se=2018-09-14T19%3A28%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-autogen/com.microsoft.azure.sdk.iot.service.transport._transport_utils.yml](https://github.com/Azure/azure-docs-sdk-java/blob/new-java-toc/docs-ref-autogen/com.microsoft.azure.sdk.iot.service.transport._transport_utils.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.service.transport._transport_utils.javaserviceclientidentifier?view=azure-java-stable&branch=pr-en-us-568) (azure-java-stable) |
[docs-ref-conceptual/toc.yml](https://github.com/Azure/azure-docs-sdk-java/blob/new-java-toc/docs-ref-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/java/azure/includes/azure-toolkit-additional-resources?view=azure-java-stable&branch=pr-en-us-568) (azure-java-stable) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C14%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201808141853562451-568%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Gk5j36Y5u74fDsrie6uHDSLRTwS8cnUAZP2WwVctlUg%3D&st=2018-08-14T21%3A23%3A47Z&se=2018-09-14T21%3A28%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by JonathanGiles** [comment]
LGTM!

**Pull request merged**
