### PR TITLE
Turn on issues/feedback control

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 75**: **[Error]** Invalid syntax in W:\one0-s\docfx.json. Please validate your syntax with a JSON validator like http://jsonlint.com/ and update the json file in the repo with a correct syntax.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C24%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201803241854324333-388%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sGx73X%2F3k3RdsHJEOZKBejQoewGww3pqp3R7NlyGUcY%3D&st=2018-03-24T18%3A53%3A37Z&se=2018-04-24T18%3A58%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docfx.json](https://github.com/Azure/azure-docs-sdk-java/blob/enable-issues/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C24%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201803241858377630-388%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UW4qmmumrjFEbuVTOiZBf50lbkXHHWEvuY27t2TyYv4%3D&st=2018-03-24T19%3A19%3A49Z&se=2018-04-24T19%3A24%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by tysonn** [comment]
The build seems to not be complete, but the content appears to be correctly staged with the new feedback control.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docfx.json](https://github.com/Azure/azure-docs-sdk-java/blob/enable-issues/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C24%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201803241903323838-388%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ezqxnu%2FHFz3w%2B5UnSKS1mX4XVkCYgFoCTBIgHCLjGP8%3D&st=2018-03-24T19%3A43%3A53Z&se=2018-04-24T19%3A48%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
