### PR TITLE
Update the tutorial for AKS

### PR DESCRIPTION
**Pull request by yhqiucherry**
Change Azure Container Service to Azure Kubernetes Service and also the Azure CLI.
Update the Kubernetes configuration website.
Add links to Kubernetes in VS Code.
Update some links to AKS.
Update the screenshots.

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/deploy-spring-boot-java-web-app-on-azure.md](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-web-app-on-azure.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB01.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB02.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB02.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB05.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB05.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB06.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB06.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB07.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB07.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/SB02.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/SB02.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C5%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201807050534233847-528%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=t%2Fp8EZwOwCr1uEFmrNT6JsvBxYI8u0EWKrBJg75zbEM%3D&st=2018-07-05T06%3A04%3A24Z&se=2018-08-05T06%3A09%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/deploy-spring-boot-java-web-app-on-azure.md](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-web-app-on-azure.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB01.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB02.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB02.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB05.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB05.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB06.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB06.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB07.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB07.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/SB02.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/SB02.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C5%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201807050623543590-528%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0fD55jLNF0zSaa4ZrdH8j7Gw%2BHieYV%2F2nbJbSnATOn4%3D&st=2018-07-05T06%3A56%3A31Z&se=2018-08-05T07%3A01%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/deploy-spring-boot-java-web-app-on-azure.md](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-web-app-on-azure.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB01.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB02.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB02.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB03.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB03.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB05.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB05.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB06.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB06.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB07.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB07.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/SB02.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/SB02.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C5%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201807050704384458-528%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=imNfJEfKqJ%2Br8PoDRTf16aQ6prH3i1nMuELpsjy2dTY%3D&st=2018-07-05T07%3A34%3A17Z&se=2018-08-05T07%3A39%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/spring-framework/deploy-spring-boot-java-web-app-on-azure.md](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-web-app-on-azure.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB01.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB01.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB02.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB02.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB05.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB05.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB06.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB06.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB07.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/KB07.png) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/SB02.png](https://github.com/yhqiucherry/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/media/deploy-spring-boot-java-app-on-kubernetes/SB02.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C5%5C5de83821-f44b-0e93-473e-c19393f102fe%5CPullRequest%5C201807050705485199-528%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=I3cxAI9yGVePVks25UWNQHGeguAtPd0u5bq5TaX4C%2B4%3D&st=2018-07-05T08%3A09%3A27Z&se=2018-08-05T08%3A14%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kyliel** [comment]
@rmcmurray, Could you please help review this PR? As you know, AKS is GA now. So we would like to update the Java guidance for AKS to ensure everything work fine. Thank you. 

•	Change Azure Container Service to Azure Kubernetes Service and also the Azure CLI.
•	Update the Kubernetes configuration website.
•	Add links to Kubernetes in VS Code, e.g. [Authenticate with Azure Container Registry from Azure Kubernetes Service] to grant AKS access to ACR.
•	Update some links to AKS.
•	Update the screenshots.

**Pull request closed without merging**
